Repository provectus/kafka-ui, pull requests merged in 2021-10, with the labels that each got.

#926 ISSUE-925 Added delete,compact topics config
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/CleanupPolicy.java
Labels: bug, backend

#935 Fix environment typo
  docker-compose.md
Labels: type/documentation, status/accepted

#939 Fix unsupported DESCRIBE_CONFIGS
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerServiceImpl.java
Labels: type/enhancement, scope/backend, status/confirmed

#991 #980: sanitize credentials in Kafka Connector configs. Add a warning to edit page when people try to edit configs with obfuscated field
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/__snapshots__/Edit.spec.tsx.snap
Labels: type/enhancement, scope/backend, scope/frontend, dependencies
