Repository provectus/kafka-ui, pull requests merged in 2021-09, with the labels that each got.

#818 JMX SSL and auth
  README.md
  docker/jmx/clientkeystore
  docker/jmx/clienttruststore
  docker/jmx/jmxremote.access
  docker/jmx/jmxremote.password
  docker/jmx/serverkeystore
  docker/jmx/servertruststore
  docker/kafka-ui-jmx-secured.yml
  docker/kafka-ui-zookeeper-ssl.yml
  kafka-ui-api/Dockerfile
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/JmxConnectionInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxPoolFactory.java
Labels: enhancement, backend, java

#880 ISSUE-876 Fixed array types to oneof for js support
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
Labels: backend

#881 Fix redirect after resetting consumer group offsets
  kafka-ui-react-app/src/redux/reducers/consumerGroups/selectors.ts
Labels: frontend

#883 Rewrite the message generation to json-schema-faker and the message validation to ajv
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/validateMessage.ts
Labels: bug, frontend

#903 Property to tune WebClient's max buffer sized added
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
Labels: enhancement, backend
