Repository provectus/kafka-ui, pull requests merged in 2021-08, with the labels that each got.

#771 #243 #244 Delete topics and topics messages using multi-selection
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
Labels: frontend

#731 Update contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#816 Fix kafka-ui image in kafka-ui-connectors.yaml
  docker/kafka-ui-connectors.yaml
Labels: bug

#791 Upgrade kafka to 2.8
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/OffsetsSeekTest.java
  pom.xml
Labels: backend, dependencies

#768 Issue#727 disable deleting
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/Constants.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/contexts/ClusterContext.ts
Labels: backend

#802 [Draft] Refactored topic creation form state management
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/New/NewContainer.ts
  kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topics.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: bug, frontend

#843 ISSUE-841 Fix null valued headers deserialisation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
Labels: bug, backend
