Repository provectus/kafka-ui, pull requests merged in 2021-06, with the labels that each got.

#511 Add ability to use custom basePath
  README.md
  docker/kafka-ui-reverse-proxy.yaml
  docker/proxy.conf
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/ProtobufFileRecordDeserializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/RecordDeserializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/SchemaRegistryRecordDeserializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/SimpleRecordDeserializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/NumberUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ResourceUtil.java
  kafka-ui-react-app/.env
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/public/index.html
  kafka-ui-react-app/src/index.tsx
  kafka-ui-react-app/src/lib/constants.ts
Labels: backend, enhancement, frontend, help wanted, wip

#523 #518 Fixed backend page size
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ClusterServiceTest.java
Labels: backend

#577 #122 Added messages reordering
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumingService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
Labels: backend

#584 #573 added sasl plain example
  docker/jaas/client.properties
  docker/jaas/kafka_server.conf
  docker/kafka-ui-sasl.yaml
Labels: backend, documentation

#586 #581 Skip trailing slash
  docker/kafka-ui-sasl.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java
Labels: backend

#587 Adding details of KafkaConnect environments in the readme
  README.md
Labels: documentation
