Repository provectus/kafka-ui, pull requests merged in 2021-07, with the labels that each got.

#607 #122 Fixed compacted topics backward reading
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
Labels: backend

#605 #234: Consumer group offsets reset implementation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: backend

#673 Implements #610
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersContainer.ts
  kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx
  kafka-ui-react-app/src/components/Brokers/__test__/__snapshots__/Brokers.spec.tsx.snap
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClusterWidget.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/__snapshots__/ClusterWidget.spec.tsx.snap
  kafka-ui-react-app/src/redux/reducers/brokers/selectors.ts
Labels: enhancement, frontend

#695 Replace favicon
  .github/workflows/pr-checks.yaml
  kafka-ui-react-app/public/favicon.ico
Labels: enhancement, frontend

#693 Forward schema registry errors to API
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/schemaregistry/ErrorResponse.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: backend, enhancement, java

#709 Create JDBC Source and Sink connectors from docker-compose
  docker/connectors/sink-activities.json
  docker/connectors/source-activities.json
  docker/connectors/start.sh
  docker/kafka-ui-connectors.yaml
  docker/postgres/Dockerfile
  docker/postgres/data.sql
Labels: backend, testing

#719 [issue-698] Fix docker-compose with connectors
  docker/kafka-connect/Dockerfile
  docker/kafka-ui-connectors.yaml
Labels: backend, testing

#682 Add KSQL DB support
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KsqlClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/KsqlDbNotFoundException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KsqlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/BaseStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/CreateStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/DescribeStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/DropStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/ExplainStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/SelectStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/TerminateStrategy.java
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KsqlServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/CreateStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/DescribeStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/DropStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/ExplainStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/SelectStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/TerminateStrategyTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: backend

#730 Issue#701 brokers config
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalBrokerConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: backend

#746 [#710] feat(react-app): call fetchTopics on toggle show internal topics
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: frontend

#751 #702 Supported incremental config update for brokers
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/InvalidRequestApiException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/LogDirsTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: backend

#752 fix schemaRegistry property by adding checks
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
Labels: backend, bug

#722 TLS enabled zookeeper
  README.md
  docker/kafka-ui-zookeeper-ssl.yml
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ZooKeeperException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
  pom.xml
Labels: backend, dependencies, documentation, enhancement, java
