Repository provectus/kafka-ui, pull requests merged in 2021-05, with the labels that each got.

#426 Use spring oauth2 starter as dependency
  kafka-ui-api/pom.xml
Labels: backend, enhancement

#427 Remove default cluster configuration.
  kafka-ui-api/src/main/resources/application.yml
Labels: backend, enhancement

#428 Do not try to connect to zookeeper if connection string is empty
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
Labels: backend

#504 [Kafka Connect] Fix getting list of connector's topics
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaConnectMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/connect/InternalConnectInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-connect-api.yaml
Labels: bug, enhancement
