Repository provectus/kafka-ui, pull requests merged in 2021-03, with the labels that each got.

#256 added features field to kafka cluster
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: backend, enhancement

#312 ISSUE-309: Topic create & update models split
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/ReadOnlyModeTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
Labels: backend, frontend

#311 [CHORE] Update react app readme
  kafka-ui-react-app/README.md
Labels: documentation
