Repository provectus/kafka-ui, pull requests merged in 2021-11, with the labels that each got.

#1041 Fix topics pagination
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
Labels: type/bug, scope/frontend

#1061 Added a gh-action for the contributors
  .github/workflows/welcome-first-time-contributors.yml
Labels: scope/infrastructure

#1065 Fix 4w time to retain selector value
  kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetainBtns.tsx
Labels: type/bug, scope/frontend

#1074 Enable spring boot actuators including health and info
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/resources/application.yml
Labels: type/enhancement, scope/backend, status/accepted, scope/infrastructure

#1080 ENCH | Add ARM platform support for docker images
  .github/workflows/master.yaml
  .github/workflows/release.yaml
Labels: type/enhancement, scope/infrastructure

#1085 Fix jar hell
  kafka-ui-e2e-checks/pom.xml
  pom.xml
Labels: type/bug, scope/backend, dependencies

#1089 Fix health/readiness path
  charts/kafka-ui/templates/deployment.yaml
Labels: type/enhancement, scope/infrastructure

#1036 Metrics & cache refactoring
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ClustersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/CleanupPolicy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalBrokerConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalLogDirStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalPartition.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalPartitionsOffsets.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopicConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/PartitionsStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/Constants.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServiceTest.java
Labels: scope/backend, type/refactoring, status/accepted

#1105 Create security policy
  SECURITY.md
Labels: type/documentation

#1090 Bump avro dependency version
  pom.xml
Labels: scope/backend, dependencies, type/security

#1107 #1106 Fixed segment size display on details page
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend, scope/frontend

#1108 Workflows to deploy and remove custom env from branches
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  charts/kafka-ui/index.yaml
Labels: status/accepted, scope/infrastructure

#1122 change_git_credentials_2shared_account
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  .github/workflows/master.yaml
Labels: type/enhancement, scope/infrastructure

#1123 ISSUE-874: Using AdminClient for offsets retrieval instead of Consumer
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
Labels: scope/backend, type/refactoring, status/accepted

#1125 The highest logging level is "trace", not "all"
  README.md
Labels: type/documentation, type/enhancement, status/accepted

#1124 Refactor Alerts component
  kafka-ui-react-app/src/components/Alert/Alert.styled.ts
  kafka-ui-react-app/src/components/Alert/Alert.tsx
  kafka-ui-react-app/src/components/Alert/__tests__/Alert.spec.tsx
  kafka-ui-react-app/src/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap
  kafka-ui-react-app/src/theme/index.scss
Labels: scope/frontend, type/refactoring

#1130 ISSUE-1128: Add respect to cluster's order in ClustersStorage
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
Labels: type/bug, scope/backend

#1129 Refactor tests
  kafka-ui-react-app/.eslintrc.json
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Alert/__tests__/Alert.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx
Labels: scope/frontend, type/refactoring

#1136 AdminClient creation error handling fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
Labels: type/bug, scope/backend, status/accepted

#1135 Bump jackson-databind-nullable
  pom.xml
Labels: scope/backend, dependencies, type/security

#1145 Metrics collection init & stacktrace addition to error responses
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, type/chore

#1127 App layout update
  kafka-ui-react-app/src/components/Alert/Alert.tsx
  kafka-ui-react-app/src/components/App.scss
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterMenuItem.styled.ts
  kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterMenuItem.tsx
  kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/ClusterTab.styled.ts
  kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/ClusterTab.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenu.spec.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/__snapshots__/ClusterMenuItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Nav/__tests__/__snapshots__/Nav.spec.tsx.snap
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetain.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
  kafka-ui-react-app/src/components/__tests__/__snapshots__/App.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.styled.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/Input/Input.styled.ts
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Input/InputIcon.styled.ts
  kafka-ui-react-app/src/components/common/Input/InputLabel.styled.ts
  kafka-ui-react-app/src/components/common/PageLoader/PageLoader.tsx
  kafka-ui-react-app/src/components/common/PageLoader/__tests__/__snapshots__/PageLoader.spec.tsx.snap
Labels: type/enhancement, scope/frontend, status/accepted
