Repository provectus/kafka-ui, pull requests merged in 2021-12, with the labels that each got.

#1149 Added Connector examples (GitHub Source, S3 Sink)
  docker/connectors/github-source.json
  docker/connectors/s3-sink.json
  docker/kafka-connect/Dockerfile
  docker/kafka-ui-connectors.yaml
  docker/kafka-ui.yaml
Labels: type/documentation, type/enhancement, scope/infrastructure

#1169 Changed generator-cli version, added rimraf library
  kafka-ui-react-app/openapitools.json
  kafka-ui-react-app/package.json
Labels: type/bug, scope/infrastructure

#1160 [kafka-ui chart] Add extra podLabels and ingress/egress custom rules
  .gitignore
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/README.md
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/templates/networkpolicy-egress.yaml
  charts/kafka-ui/templates/networkpolicy-ingress.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, status/accepted, scope/infrastructure, helm

#1181 Update SSO guide
  guides/SSO.md
Labels: type/documentation

#1187 Kafka API timeout fixes + doc
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/main/resources/application-sdp.yml
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/test/resources/application-test.yml
Labels: type/enhancement, scope/backend

#1180 Dependabot: support backend and github actiond
  .github/dependabot.yml
Labels: type/enhancement, scope/backend, status/accepted, scope/infrastructure

#866 627: tests on crud kafka connectors
  .github/workflows/e2e-checks.yaml
  kafka-ui-api/pom.xml
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-e2e-checks/src/main/resources/config_for_create_connector.json
  kafka-ui-e2e-checks/src/main/resources/config_for_create_connector_via_api.json
  kafka-ui-e2e-checks/src/main/resources/config_for_update_connector.json
  kafka-ui-e2e-checks/src/main/resources/delete_connector_config.json
  kafka-ui-e2e-checks/src/main/resources/message_content_create_topic.json
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/extensions/FileUtils.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/helpers/ApiHelper.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorUpdateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/TopicView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA

#1214 provide github token to infra repo
  .github/workflows/branch-deploy.yml
  .github/workflows/master.yaml
Labels: scope/infrastructure

#1067 Added cleanupPolicy to topic details
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: type/bug, scope/backend, scope/frontend

#1220 Fix image registry in helm chart
  charts/kafka-ui/templates/deployment.yaml
Labels: type/bug, scope/infrastructure, helm

#1161 Ksql functionality reimplemented
  docker/kafka-ui-connectors.yaml
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/antlr4/ksql/KsqlGrammar.g4
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/KsqlApiException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlGrammar.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/DynamicParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: type/enhancement, scope/backend

#1237 terraform_deploy_workflow
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1239 Feature/terraform deploy workflow
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1241 Feature/terraform deploy workflow
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1249 add image registry param to values.yaml in kafka-ui chart
  charts/kafka-ui/values.yaml
Labels: scope/infrastructure

#1247 Changed connect counter
  kafka-ui-react-app/src/components/Connect/List/List.tsx
Labels: type/bug, scope/frontend

#1251 [kafka-ui chart] Fix image registry
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/values.yaml
Labels: type/bug, status/accepted, scope/infrastructure

#1256 Feature/deploy public env from branch
  .github/workflows/branch-deploy.yml
  .github/workflows/master.yaml
Labels: scope/infrastructure

#1260 use label name as trigger for public deployment
  .github/workflows/branch-deploy.yml
Labels: scope/infrastructure

#1259 Issues/1227 Adjust font in the selection/sorting area in Topics, Dropdown list of partitions shrinks in Search line for Messages.
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts
Labels: type/bug, scope/frontend, redesign

#1262 Refactoring: cluster storage usage removed from SchemaRegistryService
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: scope/backend, type/refactoring

#1269 Add possibility to run kafka-ui container on ARM64
  kafka-ui-api/Dockerfile
Labels: scope/backend, scope/infrastructure, status/feature_testing_public

#1285 Use kafka-ui-infra token in terraform deploy workflow.
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1286 Bump github-status-action
  .github/workflows/e2e-checks.yaml
Labels: type/security, scope/infrastructure

#1287 Use kafka-ui-infra token in terraform deploy workflow.
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1297 add possibility to run tf from branch
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#1231 Fix CVE-2021-44228
  README.md
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KsqlClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AuthController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ClustersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxPoolFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/NumberUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekBackward.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekForward.java
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/main/resources/log4j2.xml
  kafka-ui-api/src/main/resources/logback-spring.xml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/ReadOnlyModeTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
Labels: type/bug, scope/backend, type/security

#1173 LDAP authentication
  docker/auth-ldap.yaml
  docker/kafka-cluster-sr-auth.yaml
  docker/kafka-clusters-only.yaml
  docker/kafka-ui-auth-context.yaml
  docker/kafka-ui-connectors.yaml
  docker/kafka-ui-jmx-secured.yml
  docker/kafka-ui-zookeeper-ssl.yml
  docker/kafka-ui.yaml
  etc/checkstyle/checkstyle.xml
  guides/SSO.md
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/SecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AbstractAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/DisabledAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.java
  kafka-ui-api/src/main/resources/application-gauth.yml
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/test/resources/application-test.yml
  kafka-ui-react-app/docker-compose.yaml
Labels: type/enhancement, scope/backend, type/dependencies

#1270 Bugfix/issue 1250 schema registry back compatibility
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/SchemaTypeIsNotSupportedException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: type/bug, scope/backend

#1312 Disabled negative values.
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
Labels: type/enhancement, scope/frontend, redesign

#1303 Issues/1265
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Schemas/New/__test__/__snapshots__/New.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/common/Metrics/Indicator.tsx
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
  kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
  kafka-ui-react-app/src/lib/yupExtended.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend, redesign

#1064 Allow empty key when producing messages
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/SimpleRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/SchemaRegistryRecordDeserializerTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Alerts/Alert.styled.ts
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessageContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/validateMessage.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/validateMessage.ts
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/redux/actions/__test__/thunks/topics.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/reducers/alerts/alertsSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: type/enhancement, scope/backend, scope/frontend

#1321 remove custom kafka-ui application in argocd when PR was unlabeled or…
  .github/workflows/branch-remove.yml
Labels: scope/infrastructure

#1339 Fix healthchecks
  kafka-ui-api/src/main/resources/application.yml
Labels: type/bug, scope/backend

#1340 Update ingress.yaml in kafka-ui chart to support kubernetes 1.22+
  charts/kafka-ui/templates/ingress.yaml
Labels: type/enhancement, scope/infrastructure, helm

#1342 Fix NPE on producing a message
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
Labels: type/bug, scope/backend, type/regression

#1345 enhancement to support ingress api 1.22+
  charts/kafka-ui/templates/ingress.yaml
Labels: type/enhancement, scope/infrastructure, helm
