Repository provectus/kafka-ui, pull requests merged in 2022-07, with the labels that each got.

#2081 Use pnpm
  .github/workflows/frontend.yaml
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-react-app/.gitignore
  kafka-ui-react-app/README.md
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  pom.xml
Labels: scope/frontend, status/triage

#2234 Update logdir label
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
Labels: scope/frontend, status/accepted, type/chore

#1951 Update product version on AWS Marketplace
  .github/workflows/aws_publisher.yaml
Labels: scope/infrastructure, type/feature

#2246 Update issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/k8s.md
  .github/ISSUE_TEMPLATE/question.md
Labels: scope/infrastructure

#2248 Update running.md
  documentation/project/contributing/running.md
Labels: type/documentation

#2191 Added key-value form for stream parameters
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
Labels: type/enhancement, scope/frontend

#2259 Publish and delete docker image in public ecr
  .github/workflows/build-public-image.yml
  .github/workflows/delete-public-image.yml
Labels: scope/infrastructure, type/feature

#2056 Active Directory support for LDAP
  documentation/compose/auth-ldap.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
Labels: type/enhancement, scope/backend, status/accepted

#2233 [e2e] Qase.io integration
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/extensions/FileUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/extensions/QaseExtension.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/extensions/WaitUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/ApiHelper.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/Helpers.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/TestConfiguration.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ProduceMessagePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorUpdateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/screenshots/NoReferenceScreenshotFoundException.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/screenshots/Screenshooter.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/BrowserUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/CamelCaseToSpacedDisplayNameGenerator.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/MethodNameUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/Status.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/TestCaseGenerator.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/annotation/AutomationStatus.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/annotation/Suite.java
  kafka-ui-e2e-checks/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: type/enhancement, scope/QA

#2286 Removes all the unused code from app
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/BrokerLogdir.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.styled.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/fixtures.ts
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/KsqlDbItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/InfoModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/fixtures.ts
  kafka-ui-react-app/src/components/common/Dropdown/DropdownItem.tsx
  kafka-ui-react-app/src/components/common/Switch/Switch.tsx
  kafka-ui-react-app/src/components/common/heading/Heading.styled.tsx
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/interfaces/alerts.ts
  kafka-ui-react-app/src/redux/interfaces/broker.ts
  kafka-ui-react-app/src/redux/interfaces/cluster.ts
  kafka-ui-react-app/src/redux/interfaces/index.ts
  kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts
  kafka-ui-react-app/src/redux/interfaces/loader.ts
  kafka-ui-react-app/src/redux/interfaces/schema.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
  kafka-ui-react-app/src/redux/reducers/loader/loaderSlice.ts
  kafka-ui-react-app/src/redux/reducers/schemas/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: scope/frontend, type/refactoring, type/chore

#2290 Upgrade dependancies
  kafka-ui-react-app/jest.config.ts
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/__test__/EditorViewer.spec.tsx
  kafka-ui-react-app/src/components/common/Navigation/Navbar.styled.ts
  kafka-ui-react-app/src/lib/hooks/api/brokers.ts
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, type/dependencies

#2296 docs: Fix typo in JMXPORT description
  README.md
Labels: type/documentation

#2299 Upgrade redux
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/lib/fixtures/kafkaConnect.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/store/configureStore/mockStoreCreator.ts
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, type/chore, status/feature_testing, type/dependencies

#2300 Upgrade RQ to v4
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/BrokerLogdir.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/__test__/BrokerLogdir.spec.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/Brokers/utils/__test__/translateLogdirs.spec.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListPage.spec.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenu.spec.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/Nav.spec.tsx
  kafka-ui-react-app/src/lib/fixtures/brokers.ts
  kafka-ui-react-app/src/lib/fixtures/clusters.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/kafkaConnect.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/brokers.ts
  kafka-ui-react-app/src/lib/hooks/api/clusters.ts
  kafka-ui-react-app/src/lib/hooks/api/kafkaConnect.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: scope/frontend, type/dependencies

#2313 fixing create schema page validation issue
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/List/ActionsCell/ActionsCell.tsx
Labels: type/bug, good first issue, scope/frontend

#2305 fixing newest first mode issue
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#2312 Use react-hot-toaster for alerts
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Alerts/Alerts.tsx
  kafka-ui-react-app/src/components/Alerts/__tests__/Alerts.spec.tsx
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/common/Alert/Alert.styled.ts
  kafka-ui-react-app/src/components/common/Alert/Alert.tsx
  kafka-ui-react-app/src/components/common/Alert/__tests__/Alert.spec.tsx
  kafka-ui-react-app/src/components/common/Metrics/Indicator.tsx
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
  kafka-ui-react-app/src/lib/errorHandling.ts
  kafka-ui-react-app/src/lib/errorHandling.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
  kafka-ui-react-app/src/redux/interfaces/alerts.ts
  kafka-ui-react-app/src/redux/interfaces/index.ts
  kafka-ui-react-app/src/redux/reducers/alerts/alertsSlice.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/chore, status/feature_testing

#2318 Fixed ingress template for k8s version older than 1.19
  .github/workflows/helm.yaml
  charts/kafka-ui/templates/ingress.yaml
Labels: type/bug, scope/k8s

#2355 New Dropdown component
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/List/ActionsCell/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.styled.ts
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.tsx
  kafka-ui-react-app/src/components/common/Dropdown/DropdownDivider.tsx
  kafka-ui-react-app/src/components/common/Dropdown/DropdownItem.tsx
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/Dropdown.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/DropdownItem.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/index.ts
  kafka-ui-react-app/src/theme/index.scss
  kafka-ui-react-app/src/theme/minireset.css
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, status/feature_testing
