Repository provectus/kafka-ui, pull requests merged in 2022-06, with the labels that each got.

#2092 Remove History from packages
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
Labels: scope/frontend, type/chore

#2073 UI improvement for 'Partition' dropdown within 'Produce Message' form
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
Labels: type/bug, good first issue, scope/frontend

#2093 Adding AsyncRequestStatus enum to avoid possible gramatical issues
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/lib/constants.ts
  kafka-ui-react-app/src/redux/interfaces/loader.ts
  kafka-ui-react-app/src/redux/reducers/clusters/clustersSlice.ts
  kafka-ui-react-app/src/redux/reducers/connect/selectors.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/selectors.ts
  kafka-ui-react-app/src/redux/reducers/loader/loaderSlice.ts
  kafka-ui-react-app/src/redux/reducers/loader/selectors.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: scope/frontend, type/refactoring, type/chore

#2094 Adding success alert message for topic deletion
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend

#2101 Bump urlchecker-action version
  .github/workflows/documentation.yaml
Labels: type/documentation, scope/infrastructure

#2060 Fix helm icon URL
  charts/kafka-ui/Chart.yaml
Labels: type/bug, scope/k8s

#2106 Fix basic auth logout page
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
Labels: type/bug, scope/backend

#2095 Fixing problem of endless loading after deleting multiple topics
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend

#2099 Fixing connector't tasks count update is not available without refreshing
  kafka-ui-react-app/src/redux/reducers/connect/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/connectSlice.ts
Labels: type/bug, scope/frontend

#2100 Fixing schema version compare version path issue
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Schemas.tsx
Labels: type/bug, scope/frontend

#2104 Adding success alert for topic recreation and fixed select arrow posi…
  kafka-ui-react-app/src/components/common/Icons/DropdownArrowIcon.tsx
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend

#2098 Using new API endpoint for KSQLDB instead of deprecated one
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/__test__/ListItem.spec.tsx
  kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
Labels: scope/frontend

#2126 Added buttons wrapping
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/common/PageHeading/PageHeading.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#1543 Fix tests. Change folders structure
  .github/workflows/e2e-checks.yaml
  documentation/compose/kafka-ui-connectors.yaml
  kafka-ui-e2e-checks/README.md
  kafka-ui-e2e-checks/docker/selenoid.yaml
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-e2e-checks/screenshots/main.png
  kafka-ui-e2e-checks/selenoid/config/browsers.json
  kafka-ui-e2e-checks/src/main/resources/config_for_create_connector.json
  kafka-ui-e2e-checks/src/main/resources/config_for_create_connector_via_api.json
  kafka-ui-e2e-checks/src/main/resources/config_for_update_connector.json
  kafka-ui-e2e-checks/src/main/resources/delete_connector_config.json
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/TestConfiguration.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/helpers/ApiHelper.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorUpdateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/ConnectorsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/TopicView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/connector/ConnectorUpdateView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/utils/BrowserUtils.java
  pom.xml
Labels: type/enhancement, scope/QA

#1992 Add UI for broker log dirs
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Brokers/List/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/List/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/Brokers/__tests__/Brokers.spec.tsx
  kafka-ui-react-app/src/components/Brokers/utils/translateLogdir.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/reducers/brokers/__test__/fixtures.ts
Labels: type/enhancement, scope/frontend

#2020 Helm: add support for external application config in yaml format
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/README.md
  charts/kafka-ui/templates/configmap.yaml
  charts/kafka-ui/templates/configmap_fromValues.yaml
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, scope/k8s

#2115 Fixing ksql table
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
Labels: type/bug, scope/frontend

#2130 get rid of unused bulma styles. small UI refactoring
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/Connect/Details/Details.tsx
  kafka-ui-react-app/src/components/Connect/New/New.styled.ts
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.styled.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/Topics/List/List.styled.ts
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/ConfigListItem.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/Settings.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/Settings.styled.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.styled.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx
  kafka-ui-react-app/src/components/common/DynamicTextButton/DynamicTextButton.tsx
  kafka-ui-react-app/src/components/common/DynamicTextButton/__tests__/DynamicTextButton.spec.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.styled.ts
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/StyledWrapper.styled.ts
  kafka-ui-react-app/src/components/common/Input/Input.styled.ts
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Input/InputIcon.styled.ts
  kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/Pagination.spec.tsx
  kafka-ui-react-app/src/components/common/Tabs/SecondaryTabs.styled.ts
  kafka-ui-react-app/src/components/common/Tabs/Tabs.tsx
  kafka-ui-react-app/src/components/common/Tabs/__tests__/Tabs.spec.tsx
  kafka-ui-react-app/src/components/common/table/SortableCulumnHeader/SortableColumnHeader.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/SortableColumnHeader.spec.tsx
  kafka-ui-react-app/src/theme/bulma_overrides.scss
  kafka-ui-react-app/src/theme/index.scss
  kafka-ui-react-app/src/theme/theme.ts
  kafka-ui-react-app/src/theme/variables.scss
Labels: status/triage

#2133 Use react-query for server state managment
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx
  kafka-ui-react-app/src/components/Brokers/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/index.tsx
  kafka-ui-react-app/src/lib/api.ts
  kafka-ui-react-app/src/lib/hooks/useBrokers.tsx
  kafka-ui-react-app/src/lib/hooks/useBrokersLogDirs.tsx
  kafka-ui-react-app/src/lib/hooks/useClusterStats.tsx
  kafka-ui-react-app/src/lib/hooks/useInterval.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/src/redux/reducers/brokers/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/brokers/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/brokers/brokersSlice.ts
  kafka-ui-react-app/src/redux/reducers/brokers/selectors.ts
  kafka-ui-react-app/src/redux/reducers/clusters/clustersSlice.ts
  kafka-ui-react-app/src/redux/reducers/connect/connectSlice.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
  kafka-ui-react-app/src/redux/reducers/loader/loaderSlice.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: status/triage

#1854 Add logout button UI
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
Labels: type/enhancement, scope/frontend

#2142 Import Brokers page without lazy
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
Labels: status/feature_testing

#2019 Timeouts with large amount of topics
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
Labels: type/bug, scope/backend

#2131 Burger fixed
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
Labels: type/bug, scope/frontend

#2138 Adding isWindowed column to ksql table
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.tsx
Labels: type/bug, scope/frontend

#2146 Fix possible CWE-94
  .github/workflows/backend.yml
Labels: type/security, scope/infrastructure

#2161 Not possible to add message for a topic
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
Labels: type/bug, good first issue, scope/frontend

#2153 Migrate React app to Vite
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-react-app/.babelrc
  kafka-ui-react-app/README.md
  kafka-ui-react-app/config/jest/cssTransform.js
  kafka-ui-react-app/index.html
  kafka-ui-react-app/jest.config.ts
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/sonar-project.properties
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.styled.spec.tsx
  kafka-ui-react-app/src/index.tsx
  kafka-ui-react-app/src/lib/constants.ts
  kafka-ui-react-app/src/react-app-env.d.ts
  kafka-ui-react-app/src/serviceWorker.ts
  kafka-ui-react-app/src/setupProxy.js
  kafka-ui-react-app/src/setupTests.ts
  kafka-ui-react-app/tsconfig.json
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, status/accepted, type/chore, status/feature_testing

#2145 Separating ksqlDb tables and streams by tabs
  kafka-ui-react-app/src/components/KsqlDb/KsqlDb.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/KsqlDbItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/__test__/KsqlDbItem.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/utils/ksqlRowData.ts
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/__test__/ListItem.spec.tsx
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/selectors.ts
Labels: scope/frontend, type/feature

#2179 Start use pr number instead of branch name for custom deployments
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
Labels: type/enhancement, status/accepted, scope/infrastructure

#2137 Added Social icons
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/common/Icons/DiscordIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/GitIcon.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend, status/feature_testing

#2151 Added click functionality to the row
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.style.ts
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
Labels: type/enhancement, scope/frontend

#2192 Adding asterix for custom params
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
Labels: type/bug, scope/frontend

#2201 Fixing compatibility and schema update order
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#2206 Upgrade deps
  kafka-ui-react-app/.husky/.gitignore
  kafka-ui-react-app/.husky/pre-commit
  kafka-ui-react-app/.jest/cssTransform.js
  kafka-ui-react-app/.jest/resolver.js
  kafka-ui-react-app/jest.config.ts
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ConsumerGroupsTableCells.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicsTableCells.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/validateMessage.ts
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useTableState.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: scope/frontend, status/feature_testing, type/dependencies

#2193 Fixing alert close icon position
  kafka-ui-react-app/src/components/Alerts/Alert.styled.ts
Labels: good first issue, scope/frontend, type/chore

#2176 Helm Chart Quick Start
  README.md
  charts/kafka-ui/templates/configmap_fromValues.yaml
  helm_chart.md
Labels: type/documentation, type/enhancement, scope/k8s, impact/documentation

#2219 Do not add comments if label was not set
  .github/workflows/branch-remove.yml
Labels: status/accepted, scope/infrastructure

#2187 Fixing connectors path redirection issue no to navigate dashboard
  kafka-ui-react-app/src/components/Connect/Connect.tsx
Labels: type/bug, scope/frontend
