Repository provectus/kafka-ui, pull requests merged in 2022-09, with the labels that each got.

#2484 Issue 2308: showing warning when deleting saved filter that's in use
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/FilterModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/SavedFilters.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#2509 [e2e] Get rid of 2nd cluster
  .github/workflows/e2e-checks.yaml
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/kafka-e2e.yaml
  kafka-ui-e2e-checks/README.md
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: type/enhancement, scope/QA

#2515 upd read.me
  kafka-ui-e2e-checks/README.md
Labels: type/documentation, scope/QA

#2516 fix appVersion version
  index.yaml
Labels: scope/k8s

#2508 #2180 The e letter allowed to paste into number fields
  kafka-ui-react-app/src/components/common/Input/Input.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#2447 Fix consumers sorting
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/container/KafkaConnectContainer.java
Labels: type/bug, scope/backend

#2521 Fix helm app version
  index.yaml
  kafka-ui-0.4.3.tgz
  kafka-ui-v0.4.2.tgz
Labels: scope/k8s

#2453 Enhance Documentation
  README.md
  documentation/project/contributing/README.md
  documentation/project/contributing/building.md
  documentation/project/contributing/prerequisites.md
  documentation/project/contributing/running.md
  documentation/project/contributing/software-required.md
Labels: type/documentation

#2548 add labels required by istio
  charts/kafka-ui/templates/deployment.yaml
Labels: type/enhancement, scope/k8s

#2565 upgraded jest and connected package versions
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
Labels: scope/frontend, status/feature_testing, type/dependencies

#2489 Manage broker configs
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.styled.ts
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/InputCell.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/__test__/Configs.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/CancelIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/CheckmarkIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/EditIcon.tsx
  kafka-ui-react-app/src/components/common/Input/Input.styled.ts
  kafka-ui-react-app/src/lib/fixtures/brokers.ts
  kafka-ui-react-app/src/lib/hooks/api/brokers.ts
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/enhancement, scope/frontend

#2482 Issue 2304: applying fix for saved filters cancel navigation issue
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/FilterModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/AddFilter.spec.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#2567 #1995 no URL encoding while getting schemas
  kafka-ui-react-app/src/components/common/NewTable/LinkCell.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#2574 New documentation for building and running without docker
  README.md
  documentation/compose/kafka-ssl.yml
  documentation/project/contributing/building-and-running-without-docker.md
  documentation/project/contributing/building.md
  documentation/project/contributing/prerequisites.md
  kafka-ui-api/src/main/resources/application-local.yml
Labels: type/documentation

#2520 Handle error message for schemas
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: type/enhancement, scope/backend

#2495 Disable schemaType during schema edit #2197
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#1063 Cognito logout + revamp
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/oauth-cognito.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CognitoOidcLogoutSuccessHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/CognitoOAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/DisabledAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/props/CognitoProperties.java
Labels: type/enhancement, scope/backend, impact/documentation

#2589 Revert "add labels required by istio"
  charts/kafka-ui/templates/deployment.yaml
Labels: scope/k8s

#2594 Get rid of dockerfile-maven-plugin
  kafka-ui-api/pom.xml
  pom.xml
Labels: scope/backend, type/chore

#2592 Fix flaky backend test
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/MessageFiltersTest.java
Labels: scope/backend, type/chore

#2591 Added method isSchemaDropDownDisabled() for handling error when updat…
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
Labels: scope/QA

#2598 Build local image upon e2e
  .github/workflows/e2e-checks.yaml
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA, scope/infrastructure

#2595 Update docs on docker plugin
  documentation/project/contributing/building-and-running-without-docker.md
  documentation/project/contributing/building.md
Labels: type/documentation

#2597 Rename "Relevant" version of a schema to "Actual"
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/LatestVersionItem.spec.tsx
Labels: scope/frontend, type/chore

#2604 Change the "Back to custom filters" link text within Saved filters
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/SavedFilters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/SavedFilters.spec.tsx
Labels: scope/frontend, type/chore

#2602 Add "Total lag" within Consumer group (#2530)
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
Labels: type/enhancement, scope/frontend

#2605 Disable ldap beans auto configuration
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/KafkaUiApplication.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
  kafka-ui-api/src/main/resources/application.yml
Labels: type/bug, scope/backend

#2610 Refactor numeric inputs logic.
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/InputCell.tsx
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/lib/hooks/api/brokers.ts
Labels: type/bug, scope/frontend, status/feature_testing

#2607 Add "Num of Topics" to Topic/Consumer tab (#2537)
  kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
Labels: scope/frontend, type/chore

#2608 Display additional fields in the table and overview
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx
  kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/SchemaVersion.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#2606 create object models and implement them into tests
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/ApiHelper.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Connector.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Schema.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Topic.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/main/resources/testData/schema_Json_Value.json
  kafka-ui-e2e-checks/src/main/resources/testData/schema_avro_for_update.json
  kafka-ui-e2e-checks/src/main/resources/testData/schema_avro_value.json
  kafka-ui-e2e-checks/src/main/resources/testData/schema_protobuf_value.txt
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: type/enhancement, scope/QA

#2617 Update typo in "Enterprise" on root Readme.md
  README.md
Labels: type/documentation

#2619 [e2e] produceMessage test
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ProduceMessagePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/ProduceMessagePanel.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
Labels: scope/QA

#2627 ForwardRecordEmitter infinite polls fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
Labels: type/bug, scope/backend, status/feature_testing

#2626 Issue#2437
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/extensions/WebUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA, type/refactoring, status/accepted

#2613 Get rid of KC edit config page
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-react-app/src/components/Connect/Connect.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.styled.ts
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/Config.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__tests__/Config.spec.tsx
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/__tests__/Connect.spec.tsx
  kafka-ui-react-app/src/lib/hooks/api/kafkaConnect.ts
  kafka-ui-react-app/src/lib/paths.ts
Labels: scope/frontend, type/chore

#2641 [e2e] upd module sctructure
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/ApiHelper.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/TestConfiguration.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorUpdateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/Source.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/FileUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WaitUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/DisplayNameGenerator.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/QaseExtension.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/TestCaseGenerator.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/annotations/AutomationStatus.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/annotations/Suite.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/enums/Status.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/screenshots/NoReferenceScreenshotFoundException.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/screenshots/Screenshooter.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/BrowserUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utils/qaseIO/MethodNameUtils.java
  kafka-ui-e2e-checks/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Config.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA, type/refactoring

#2618 Create schema view is too wide
  kafka-ui-react-app/src/components/Schemas/New/New.styled.ts
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
Labels: scope/frontend, type/chore, status/feature_testing

#2629 Implement Search within Consumer group profile
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#2649 Issue_2438
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Setup.java
Labels: type/enhancement, scope/QA, type/refactoring, status/accepted

#2620 Add serde to send message component
  kafka-ui-react-app/jest.config.ts
  kafka-ui-react-app/src/components/Connect/List/List.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Messages.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/FiltersBar/Form.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/utils/getDefaultSerdeName.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/utils.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/validateMessage.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/utils.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/validateMessage.ts
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx
  kafka-ui-react-app/src/components/contexts/TopicMessagesContext.ts
  kafka-ui-react-app/src/lib/fixtures/topicMessages.ts
  kafka-ui-react-app/src/lib/fixtures/topics.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/topicMessages.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/topics.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
  kafka-ui-react-app/src/lib/hooks/useSearch.ts
Labels: scope/frontend, status/feature_testing, type/feature

#2640 ISSUE-1572: Avro->json schema converter references fixes
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
Labels: type/bug, scope/backend, status/feature_testing

#2590 Format dates in a single place, Display build date instead of full commit hash in version info
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Indicators/Total.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
  kafka-ui-react-app/src/components/contexts/ConfirmContext.tsx
  kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
  kafka-ui-react-app/src/lib/api.ts
  kafka-ui-react-app/src/lib/constants.ts
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
  kafka-ui-react-app/src/lib/fixtures/actuatorInfo.ts
  kafka-ui-react-app/src/lib/fixtures/latestVersion.ts
  kafka-ui-react-app/src/lib/fixtures/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/actuatorInfo.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/brokers.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/clusters.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/kafkaConnect.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/latestVersion.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/timeFormat.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/topics.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/actuatorInfo.ts
  kafka-ui-react-app/src/lib/hooks/api/kafkaConnect.ts
  kafka-ui-react-app/src/lib/hooks/api/latestVersion.ts
  kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/useTimeFormat.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend

#2583 Expose build info for actuator
  kafka-ui-api/pom.xml
Labels: type/enhancement, scope/backend, status/feature_testing

#2656 [e2e] create screen facade class and refactor objects of page classes
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/Helpers.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Facade.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA

#2628 ISSUE-2080: Consumer groups not found for topic
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopicConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend, status/feature_testing

#2663 Add warning message for Danger zone in case of editing the Topic #2534
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.styled.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/chore, status/feature_testing
