Repository provectus/kafka-ui, pull requests merged in 2022-08, with the labels that each got.

#2371 Fix e2e run on m1
  kafka-ui-e2e-checks/README.md
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/helpers/TestConfiguration.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
Labels: type/bug, scope/QA

#2363 Make frontend work properly with custom context url
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java
  kafka-ui-react-app/.jest/resolver.js
  kafka-ui-react-app/index.html
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/public/favicon/favicon.ico
  kafka-ui-react-app/public/manifest.json
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListPage.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/Nav/ClusterMenu.tsx
  kafka-ui-react-app/src/components/Nav/Nav.styled.ts
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/InfoModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/SavedFilters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/SavedFilters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
  kafka-ui-react-app/src/components/common/Button/Button.styled.ts
  kafka-ui-react-app/src/components/common/Icons/ArrowDownIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/ClockIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/DeleteIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/FileIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/PlusIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/SearchIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/SpinnerIcon.tsx
  kafka-ui-react-app/src/components/common/Input/Input.styled.ts
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Metrics/Indicator.tsx
  kafka-ui-react-app/src/components/common/Search/Search.tsx
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/components/global.css.ts
  kafka-ui-react-app/src/index.tsx
  kafka-ui-react-app/src/theme/index.scss
  kafka-ui-react-app/src/theme/theme.ts
  kafka-ui-react-app/vite.config.ts
Labels: type/bug, scope/frontend

#2339 remove ksql editor unnecessary line
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
Labels: scope/frontend, type/chore

#2205 [Topics] There are default values when user try to edit topic
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/topicParamsTransformer.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/Edit/topicParamsTransformer.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend, status/feature_testing

#2360 Update kafka-clients dependency
  pom.xml
Labels: scope/backend, type/dependencies

#2368 Allow not specify image.registry in the values of the helm chart
  charts/kafka-ui/templates/_helpers.tpl
  charts/kafka-ui/templates/deployment.yaml
Labels: type/enhancement, scope/k8s

#1921 fix kafka-connect healthcheck probe
  documentation/compose/kafka-ui-connectors-auth.yaml
Labels: scope/QA, status/accepted, type/chore

#2376 New Confirmation Messages modal
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/Config.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/ActionsCell/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/SavedFilters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/SavedFilters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZoneContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/common/Alert/Alert.styled.ts
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.styled.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/__test__/ConfirmationModal.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.styled.ts
  kafka-ui-react-app/src/components/common/Dropdown/DropdownItem.tsx
  kafka-ui-react-app/src/components/common/MultiSelect/__test__/MultiSelect.styled.spec.tsx
  kafka-ui-react-app/src/components/contexts/ConfirmContext.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useConfirm.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend, type/refactoring, status/accepted, status/feature_testing

#2357 CVE fixes Q2.22
  kafka-ui-api/Dockerfile
  pom.xml
Labels: scope/backend, type/security

#1857 Drop unnecessary maven scripts
  kafka-ui-api/.mvn/wrapper/MavenWrapperDownloader.java
  kafka-ui-api/.mvn/wrapper/maven-wrapper.jar
  kafka-ui-api/.mvn/wrapper/maven-wrapper.properties
  kafka-ui-api/mvnw
  kafka-ui-api/mvnw.cmd
  kafka-ui-react-app/LICENSE
  kafka-ui-react-app/docker-compose.yaml
Labels: status/accepted, type/chore, scope/infrastructure

#2395 Disable unstable topic test
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA, type/chore

#2390 Resolve issue #2262 validate topic creation
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/backend

#2398 fixes #1622
  kafka-ui-api/pom.xml
Labels: scope/backend, type/chore

#2399 Update Alerts to use ReactNode as a message content
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/common/Alert/Alert.styled.ts
  kafka-ui-react-app/src/components/common/Alert/Alert.tsx
  kafka-ui-react-app/src/lib/errorHandling.tsx
Labels: scope/frontend, type/security

#2410 Do not display broker error as "none"
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/DescribeLogDirsMapper.java
Labels: type/enhancement, scope/backend

#2370 Fixing bug 2243 - Replication Factor validation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#2413 Topic statistics
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/__test__/Diff.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Indicators/SizeStats.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Indicators/Total.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/PartitionInfoRow.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/PartitionTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Statistics.styles.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Statistics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/__test__/Metrics.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/__test__/Statistics.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
  kafka-ui-react-app/src/components/common/NewTable/ExpanderCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/common/NewTable/TimestampCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/index.ts
  kafka-ui-react-app/src/components/common/NewTable/utils/__test__/updateSortingState.spec.ts
  kafka-ui-react-app/src/components/common/NewTable/utils/updatePaginationState.ts
  kafka-ui-react-app/src/components/common/NewTable/utils/updateSortingState.ts
  kafka-ui-react-app/src/components/common/ProgressBar/ProgressBar.styled.ts
  kafka-ui-react-app/src/components/common/ProgressBar/ProgressBar.tsx
  kafka-ui-react-app/src/components/common/ProgressBar/__test__/ProgressBar.spec.tsx
  kafka-ui-react-app/src/components/common/PropertiesList/PropertiesList.styled.tsx
  kafka-ui-react-app/src/lib/__test__/paths.spec.ts
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
  kafka-ui-react-app/src/lib/fixtures/topics.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/topics.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, status/feature_testing, type/feature

#2416 Fix unstable e2e test
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: type/bug, scope/QA

#2418 Get rid of asserts in helper classes #2295
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: type/enhancement, scope/QA

#2387 Use semver object to check version compatability in HELM Chart #2385
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/ingress.yaml
Labels: type/bug, scope/k8s

#2423 PR Reviews, Encapsulating MetricsConfig into it's own class and renaming PrometheusParser
  README.md
  documentation/compose/auth-ldap.yaml
  documentation/compose/kafka-ui-auth-context.yaml
  documentation/compose/kafka-ui-connectors-auth.yaml
  documentation/compose/kafka-ui-connectors.yaml
  documentation/compose/kafka-ui-jmx-secured.yml
  documentation/compose/kafka-ui-with-jmx-exporter.yaml
  documentation/compose/kafka-ui.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/MetricsConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxMetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/PrometheusEndpointMetricsParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/PrometheusMetricsRetriever.java
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/PrometheusEndpointMetricsParserTest.java
Labels: status/triage

#2425 Fix validation message for Topic name field
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/lib/constants.ts
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/frontend, status/feature_testing

#2422 Fix "unique" labels abbreviations
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Indicators/Total.tsx
Labels: scope/frontend, type/chore

#2426 Use new table component for topics list
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/BrokerLogdir.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/__test__/BrokerLogdir.spec.tsx
  kafka-ui-react-app/src/components/Brokers/utils/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Brokers/utils/__test__/translateLogdirs.spec.tsx
  kafka-ui-react-app/src/components/Brokers/utils/translateLogdirs.ts
  kafka-ui-react-app/src/components/Topics/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/List/BatchActionsBar.tsx
  kafka-ui-react-app/src/components/Topics/List/List.styled.ts
  kafka-ui-react-app/src/components/Topics/List/ListPage.tsx
  kafka-ui-react-app/src/components/Topics/List/TopicTable.tsx
  kafka-ui-react-app/src/components/Topics/List/TopicTitleCell.tsx
  kafka-ui-react-app/src/components/Topics/List/TopicsTable.tsx
  kafka-ui-react-app/src/components/Topics/List/TopicsTableCells.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ActionCell.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListPage.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicsTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicsTableCells.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/PartitionTable.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.styled.ts
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.tsx
  kafka-ui-react-app/src/components/common/IndeterminateCheckbox/IndeterminateCheckbox.tsx
  kafka-ui-react-app/src/components/common/NewTable/SelectRowCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/SelectRowHeader.tsx
  kafka-ui-react-app/src/components/common/NewTable/SizeCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/index.ts
  kafka-ui-react-app/src/components/common/NewTable/utils/updatePaginationState.ts
  kafka-ui-react-app/src/components/common/table/Table/TableKeyLink.styled.ts
  kafka-ui-react-app/src/lib/fixtures/brokers.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, status/feature_testing

#2444 Get rid of SmartTable component
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.style.ts
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ConsumerGroupsTableCells.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListContainer.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ConsumerGroupsTableCells.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/KsqlDbItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/__test__/KsqlDbItem.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/Schemas/List/ListItem.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.styled.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/ExpanderCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/LinkCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/SelectRowCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/SelectRowHeader.tsx
  kafka-ui-react-app/src/components/common/NewTable/SizeCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/common/NewTable/TagCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/TimestampCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/index.ts
  kafka-ui-react-app/src/components/common/Pagination/PageControl.tsx
  kafka-ui-react-app/src/components/common/Pagination/Pagination.styled.ts
  kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/PageControl.spec.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/Pagination.spec.tsx
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
  kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
  kafka-ui-react-app/src/components/common/Tag/getTagColor.ts
  kafka-ui-react-app/src/components/common/table/Table/TableKeyLink.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/lib/__test__/propertyLookup.spec.ts
  kafka-ui-react-app/src/lib/hooks/usePagination.ts
  kafka-ui-react-app/src/lib/hooks/useTableState.ts
  kafka-ui-react-app/src/lib/propertyLookup.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/fixtures.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, status/feature_testing

#2424 Request: a command to compile just kafka-ui-api, ignoring the frontend #1666
  documentation/project/contributing/building.md
  kafka-ui-api/pom.xml
Labels: type/enhancement, scope/backend, type/chore

#2448 verify Step annotation cross page methods.
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/Pages.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ProduceMessagePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
Labels: type/enhancement, scope/QA, status/accepted

#2455 Bugfix/2320 move tasks to a new table
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/Tasks.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/ExpanderCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/lib/fixtures/kafkaConnect.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/refactoring

#2400 Fix smart filters multiple conditions
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#2461 Fix e2e tests stability
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
Labels: type/bug, scope/QA

#2466 Delete of Steps package #2433
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/steps/Steps.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/steps/kafka/KafkaSteps.java
Labels: type/enhancement, scope/QA, type/refactoring

#2470 get rid of SheakyThrows annotation
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/extensions/FileUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/screenshots/Screenshooter.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA, type/refactoring

#2480 Fix transient jre CVEs
  kafka-ui-api/Dockerfile
Labels: scope/backend, type/security

#2469 #2261 "Value" field is focused with adding the Custom Parameter in a …
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
Labels: scope/frontend, status/feature_testing

#2485 Redirect to topics page #2392
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Labels: type/bug, scope/frontend

#2471 Fix URL encoding while getting schemas
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
Labels: type/bug, scope/backend, type/regression

#2483 Fix subject encoding frontend (#1995)
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
  kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Schemas/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/fixtures.ts
  kafka-ui-react-app/src/lib/__test__/paths.spec.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/reducers/schemas/__test__/fixtures.ts
Labels: type/bug, scope/frontend, type/regression

#2496 update read.me file for 'kafka-ui-e2e-checks' module with actual steps
  kafka-ui-e2e-checks/README.md
Labels: type/documentation

#2503 Add arm64 kafka-ui docker compose script
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/kafka-ui-arm64.yaml
  documentation/compose/scripts/update_run.sh
Labels: type/documentation

#2277 [2163] Make message timestamp format configurable #2163
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/InfoController.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#2493 Add full message details to export
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Labels: type/bug, scope/frontend
