Repository provectus/kafka-ui, pull requests merged in 2022-02, with the labels that each got.

#1526 Feature/issue 1525 add sort order consumer page
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#1524 [Fixes #1520] Too short visible list for Schema compatibility level selector
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, type/regression

#1514 [Fixes #1510] UI, Critical: retention.bytes parameter set to 0
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetain.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/lib/constants.ts
Labels: type/bug, scope/frontend

#1531 Config Sanitizer disable property added
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
Labels: type/enhancement, scope/backend, status/accepted, impact/changelog

#1536 fixed Code Smells from PR 1494
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
Labels: scope/frontend

#1381 Massive documentation update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  docker-openjdk/Dockerfile
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/auth-ldap.yaml
  documentation/compose/connectors/github-source.json
  documentation/compose/connectors/s3-sink.json
  documentation/compose/connectors/sink-activities.json
  documentation/compose/connectors/source-activities.json
  documentation/compose/connectors/start.sh
  documentation/compose/jaas/client.properties
  documentation/compose/jaas/kafka_server.conf
  documentation/compose/jaas/schema_registry.jaas
  documentation/compose/jaas/schema_registry.password
  documentation/compose/jmx/clientkeystore
  documentation/compose/jmx/clienttruststore
  documentation/compose/jmx/jmxremote.access
  documentation/compose/jmx/jmxremote.password
  documentation/compose/jmx/serverkeystore
  documentation/compose/jmx/servertruststore
  documentation/compose/kafka-cluster-sr-auth.yaml
  documentation/compose/kafka-clusters-only.yaml
  documentation/compose/kafka-connect/Dockerfile
  documentation/compose/kafka-ui-auth-context.yaml
  documentation/compose/kafka-ui-connectors.yaml
  documentation/compose/kafka-ui-jmx-secured.yml
  documentation/compose/kafka-ui-reverse-proxy.yaml
  documentation/compose/kafka-ui-sasl.yaml
  documentation/compose/kafka-ui-traefik-proxy.yaml
  documentation/compose/kafka-ui-zookeeper-ssl.yml
  documentation/compose/kafka-ui.yaml
  documentation/compose/message.json
  documentation/compose/postgres/Dockerfile
  documentation/compose/postgres/data.sql
  documentation/compose/proxy.conf
  documentation/compose/traefik/kafkaui.yaml
  documentation/guides/AWS_IAM.md
  documentation/guides/SASL_SCRAM.md
  documentation/guides/SSO.md
  documentation/images/Connector_Topic_Consumer.gif
  documentation/images/Create_message_kafka-ui.gif
  documentation/images/Create_schema.gif
  documentation/images/Create_topic_kafka-ui.gif
  documentation/images/Interface.gif
  documentation/images/Schema_Topic.gif
  documentation/images/free-open-source.svg
  documentation/images/kafka-ui-logo.png
  documentation/project/ROADMAP.md
  documentation/project/contributing/README.md
  documentation/project/contributing/building.md
  documentation/project/contributing/running.md
  documentation/project/contributing/set-up-git.md
  documentation/project/contributing/software-required.md
  documentation/project/contributing/testing.md
  images/kafka-ui-logo.png
Labels: type/documentation

#1538 [Fixes #1534] No originally selected custom parameters in topic's edit tab
  .github/workflows/backend.yml
  .github/workflows/e2e-checks.yaml
  kafka-ui-react-app/sonar-project.properties
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.styled.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/__snapshots__/DangerZone.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/lib/constants.ts
Labels: type/bug, scope/frontend

#1527 Improve test coverage
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/utils.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/utils.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/ConfigListItem.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/Settings.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/ConfigListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__tests__/Topic.spec.tsx
Labels: good first issue, scope/frontend, type/chore

#1540 [ISSUE-1533] Update visible list in dropdown selector
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
Labels: type/bug, good first issue, scope/frontend

#1542 Hide 'Clear Messages' button on Topic without Delete Clean Up Policy
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
Labels: type/bug, good first issue, scope/frontend, type/regression

#1548 use lowercase for env names even if branch name consist uppercase sym…
  .github/workflows/branch-deploy.yml
Labels: type/enhancement, status/accepted, scope/infrastructure

#1489 Fixed issue/1465 partially got rid of enzyme in tests
  kafka-ui-react-app/src/components/Connect/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/Connect/__tests__/Connect.spec.tsx
  kafka-ui-react-app/src/components/Connect/__tests__/__snapshots__/Connect.spec.tsx.snap
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/Dropdown.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/DropdownItem.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/__snapshots__/Dropdown.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Dropdown/__tests__/__snapshots__/DropdownItem.spec.tsx.snap
  kafka-ui-react-app/src/components/common/DynamicTextButton/__tests__/DynamicTextButton.spec.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/__tests__/SQLEditor.spec.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/__tests__/__snapshots__/SQLEditor.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Search/__tests__/Search.spec.tsx
  kafka-ui-react-app/src/components/common/Search/__tests__/__snapshots__/Search.spec.tsx.snap
Labels: scope/frontend, type/refactoring

#1530 [Fixed issue/1449] Refactored ksqlDb reducer to reduxjs/toolkit approach
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts
  kafka-ui-react-app/src/redux/actions/__test__/thunks/ksqlDb.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/index.ts
  kafka-ui-react-app/src/redux/actions/thunks/ksqlDb.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/__snapshots__/reducer.spec.ts.snap
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/reducer.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/selectors.ts
Labels: scope/frontend, type/refactoring

#1559 Fix maven warnings about dynamic versioning
  .github/workflows/branch-deploy.yml
  .github/workflows/master.yaml
  .github/workflows/release.yaml
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-e2e-checks/pom.xml
  pom.xml
Labels: type/bug, scope/infrastructure

#1319 Console banner change to fit new name
  kafka-ui-api/src/main/resources/banner.txt
Labels: scope/backend, type/chore

#1547 Smart filters: Groovy script messages filter implementation (reopened)
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessageFilters.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/MessageFiltersTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: scope/backend, status/feature_testing, type/feature

#1515 ISSUE-943: Topic messages tailing implementation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ConsumingStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ResultSizeLimiter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/feature

#1539 [ISSUE-1512]Added sorting by topics size
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, status/feature_testing

#1567 Issue/1512 frontend
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx
  kafka-ui-react-app/src/redux/actions/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: type/enhancement, scope/frontend, type/refactoring

#1456 [ISSUE-998][backend] Add functionality to re-create topic in one click
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/TopicRecreationException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#1575 Run the app in the container as a non-root user
  kafka-ui-api/Dockerfile
Labels: type/enhancement, scope/backend

#1570 [FIXED issue/1545] added feedback to the user when a message content is copied to clipboard
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Labels: scope/frontend, type/feature

#1583 [Issue-1490] Made adaptive height in connectors config component
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/__snapshots__/Config.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Editor/Editor.tsx
Labels: type/enhancement, good first issue, scope/frontend

#1581 Allow running sonar within PR of a fork
  .github/workflows/backend.yml
  .github/workflows/e2e-checks.yaml
  .github/workflows/frontend.yaml
Labels: scope/infrastructure

#1595 Specify distinct image tag version for helm chart
  .github/workflows/release.yaml
  charts/kafka-ui/values.yaml
Labels: type/bug, scope/infrastructure, scope/k8s

#1594 Fixed all tag-badges background colors
  kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/Utils/TagColor.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Utils/TagColor.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
Labels: type/bug, good first issue, scope/frontend

#1565 fix URP color for topcis and brokers
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
Labels: type/bug, scope/frontend

#1607 Fix workflow for documentation
  .github/workflows/documentation.yaml
Labels: type/bug, scope/infrastructure

#1610 build ami workflow for aws marketplace
  .github/workflows/aws_publisher.yaml
Labels: scope/infrastructure, type/feature

#1592 [FIXED issue/1544] Resolved bug with export of JSON message to clipboard/file
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Labels: type/bug, scope/frontend, status/accepted, status/confirmed

#1614 Do not run frontend tests upon git hooks
  kafka-ui-react-app/.husky/pre-commit
Labels: type/enhancement, scope/frontend, type/chore, scope/infrastructure

#1593 ISSUE-897: SchemaRegistryAwareRecordSerDe refactor
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/SimpleRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/MessageFormat.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonSchema.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDeTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/SimpleRecordSerDeTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDeTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
Labels: type/bug, scope/backend

#1601 ISSUE-1444: Connect RESTART_ALL_TASKS & RESTART_FAILED_TASKS
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend

#1609 Fix SR failing pending requests
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
Labels: type/bug, scope/backend

#1603 Update/fix documentation where needed
  README.md
  documentation/project/contributing/building.md
  documentation/project/contributing/running.md
  documentation/project/contributing/software-required.md
  kafka-ui-react-app/README.md
Labels: type/documentation

#1634 Trigger backend workflow on root pom.xml change
  .github/workflows/backend.yml
  .github/workflows/e2e-checks.yaml
Labels: type/bug, scope/infrastructure

#1611 [FE] Add the logo
  kafka-ui-react-app/public/favicon.ico
  kafka-ui-react-app/public/favicon/apple-touch-icon.png
  kafka-ui-react-app/public/favicon/icon-192.png
  kafka-ui-react-app/public/favicon/icon-512.png
  kafka-ui-react-app/public/favicon/icon.svg
  kafka-ui-react-app/public/index.html
  kafka-ui-react-app/public/manifest.json
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Version/Version.styled.ts
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/common/Logo/Logo.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend, status/feature_testing

#1636 Update contributing guide
  CONTRIBUTING.md
Labels: status/triage

#1641 Make Ingress resource survive k8s upgrade from 1.21 to 1.22
  charts/kafka-ui/templates/ingress.yaml
Labels: type/bug, scope/k8s

#1645 Implement a workflow to check other workflows syntax
  .github/workflows/aws_publisher.yaml
  .github/workflows/helm.yaml
  .github/workflows/release_drafter.yml
  .github/workflows/welcome-first-time-contributors.yml
  .github/workflows/workflow_linter.yaml
Labels: type/enhancement, scope/infrastructure

#1635 [Fixed issue/1620] Resolved problem with appearance of cluster name in left side
  kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.styled.ts
  kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.tsx
Labels: type/bug, scope/frontend, status/accepted, status/confirmed

#1616 [Fixed issue/1587] Got rid of react-hooks/exhaustive-deps errors
  kafka-ui-react-app/.eslintrc.json
  kafka-ui-react-app/src/components/Alerts/Alerts.tsx
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/ResultRenderer.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.route.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx
  kafka-ui-react-app/src/components/common/BytesFormatted/BytesFormatted.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.tsx
  kafka-ui-react-app/src/components/common/DynamicTextButton/DynamicTextButton.tsx
  kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx
  kafka-ui-react-app/src/components/common/Tabs/Tabs.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useSearch.ts
Labels: scope/frontend, status/accepted

#1044 #867: add a view for comparing schema versions
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.styled.ts
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/DiffContainer.ts
  kafka-ui-react-app/src/components/Schemas/Diff/__test__/Diff.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Schemas/Schemas.tsx
  kafka-ui-react-app/src/components/common/Button/Button.tsx
  kafka-ui-react-app/src/components/common/DiffViewer/DiffViewer.tsx
  kafka-ui-react-app/src/components/common/DiffViewer/__tests__/DiffViewer.spec.tsx
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/enhancement, scope/frontend, status/accepted

#1642 Add port column to brokers info
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
Labels: type/enhancement, scope/frontend

#1626 Template ingress hostname
  charts/kafka-ui/templates/ingress.yaml
Labels: type/enhancement, status/accepted, scope/k8s

#1647 Quickfix warning
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/DiffContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
Labels: type/bug, scope/frontend

#1651 Rename offsets columns and add "message count" in topic details page
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
Labels: status/triage

#1655 frontend wf restrict warnings
  .github/workflows/frontend.yaml
  kafka-ui-react-app/package.json
Labels: type/enhancement, scope/infrastructure

#1648 Code optimisations
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxMetricsName.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxMetricsValueName.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaConstants.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ResultSizeLimiter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/producer/KafkaTestProducer.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SchemaRegistryPaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
Labels: scope/backend, type/refactoring

#1652 "initializing" state added to ServerStatus enum
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#1668 add env, initContainers, volumeMounts and volumes
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, status/accepted, scope/k8s

#1681 Add cve checks wf
  .github/workflows/cve.yaml
Labels: type/enhancement, scope/infrastructure
