Repository provectus/kafka-ui, pull requests merged in 2022-11, with the labels that each got.

#2849 Full width table display in KSQL_DB page
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.styled.tsx
Labels: scope/frontend, type/chore, hacktoberfest-accepted

#2861 Add editorconfig
  .editorconfig
Labels: scope/infrastructure

#2749 [Helm] Added annotations for the deployment
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, scope/k8s, hacktoberfest-accepted

#2880 fix version and workflow
  .github/workflows/release-helm.yaml
  charts/kafka-ui/Chart.yaml
Labels: scope/infrastructure

#2879 Feature: Upgrade to Java 17 (Azul Zulu)
  .github/workflows/backend.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/cve.yaml
  .github/workflows/e2e-checks.yaml
  .github/workflows/master.yaml
  .github/workflows/release.yaml
  documentation/project/contributing/prerequisites.md
  kafka-ui-api/Dockerfile
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-e2e-checks/pom.xml
  pom.xml
Labels: scope/backend, type/dependencies

#2775 Broker configs: Display a tooltip about the source of the property #2679
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.styled.ts
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
  kafka-ui-react-app/src/components/common/Icons/InfoIcon.tsx
  kafka-ui-react-app/src/components/common/Tooltip/Tooltip.styled.ts
  kafka-ui-react-app/src/components/common/Tooltip/Tooltip.tsx
  kafka-ui-react-app/src/components/common/Tooltip/__tests__/Tooltip.spec.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/chore, status/feature_testing

#2874 Feature: Add support for multiple Protobuf files
  documentation/guides/Protobuf.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
  kafka-ui-api/src/test/resources/sensor.proto
Labels: type/enhancement, scope/backend

#2882 Bump Maven to version 3.8.6 and reduce noise
  .github/workflows/backend.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/cve.yaml
  .github/workflows/e2e-checks.yaml
  .github/workflows/master.yaml
  .github/workflows/release.yaml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  kafka-ui-e2e-checks/README.md
Labels: scope/backend, type/chore, scope/infrastructure, type/dependencies

#2691 Topic analysis improvements
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Statistics.styles.ts
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/Metrics.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/Statistics.spec.tsx
  kafka-ui-react-app/src/lib/__test__/dateTimeHelpers.spec.ts
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
Labels: type/enhancement, scope/frontend

#2894 fix TopicTest()
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/AQA

#2848 Add space to formatted sizes
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/common/BytesFormatted/BytesFormatted.styled.ts
  kafka-ui-react-app/src/components/common/BytesFormatted/BytesFormatted.tsx
  kafka-ui-react-app/src/components/common/BytesFormatted/__tests__/BytesFormatted.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
Labels: scope/frontend, type/chore, hacktoberfest-accepted

#2897 CI: Fix GitHub Actions warnings for `::set-output`
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/cve.yaml
  .github/workflows/delete-public-image.yml
  .github/workflows/master.yaml
  .github/workflows/release.yaml
Labels: type/chore, scope/infrastructure

#2898 CI: Scan Java source files with CodeQL
  .github/workflows/codeql-analysis.yml
  kafka-ui-api/pom.xml
Labels: scope/backend, status/accepted, type/chore, scope/infrastructure

#2756 #2544 message fields preview
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/PreviewModal.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/PreviewModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/PreviewModal.spec.tsx
Labels: scope/frontend, type/feature

#2814 Do not cache serdes endpoint results on frontend
  kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
Labels: type/bug, scope/frontend

#2886 Fix misplaced setting in compose files (#2601)
  documentation/compose/kafka-ui.yaml
Labels: type/documentation, type/chore

#2896 Tests: Fix `NullPointerException` in `QaseExtension` if token is unavailable
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/QaseExtension.java
Labels: type/chore, scope/AQA

#2803 Add a missing space for partitions count
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
Labels: scope/frontend, status/accepted, type/chore, hacktoberfest-accepted

#2917 Remove messages v2
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Messages.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/getDefaultSerdeName.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Advanced Filter/AdvancedFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Advanced Filter/Form.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/FiltersBar/FiltersBar.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/FiltersBar/Form.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/FiltersBar/Meta.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/FiltersBar/utils.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesTable/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesTable/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesTable/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/MessagesTable/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/StatusBar.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/utils/consumingModes.ts
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/utils/handleNextPageClick.ts
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
Labels: scope/frontend, type/chore

#2921 Non-serializable warning
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/selectors.spec.ts
Labels: scope/frontend

#2927 undefined data warning in Statistics.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/Statistics.spec.tsx
Labels: scope/frontend

#2926 Fix CVEs, Nov. 2022
  pom.xml
Labels: scope/backend, type/security

#2833 feat(kafka-connect): Implement kafka-connect mTLS configuration
  README.md
  documentation/compose/kafka-ssl-components.yaml
  documentation/compose/ssl/generate_certs.sh
  documentation/compose/ssl/kafka.keystore.jks
  documentation/compose/ssl/kafka.truststore.jks
  documentation/compose/ssl/san.cnf
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaConnectCluster.java
Labels: type/enhancement, scope/backend

#2929 Centralize dependency versions and bump where necessary
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-serde-api/pom.xml
  pom.xml
Labels: scope/backend, type/dependencies

#2940 Snappy native impl fix
  kafka-ui-api/Dockerfile
Labels: type/bug, scope/backend, status/feature_testing

#2873 [UI] Fix save to file issues with bigdecimal
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Labels: type/bug, good first issue, scope/frontend, status/accepted

#2863 Seek type field became empty with refreshing the page
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#2924 Allow Skip Certificates Verification in readiness and liveness probes
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, scope/k8s

#2910 fixed All warnings with Act function in testing library
  kafka-ui-react-app/src/components/Schemas/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListPage.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/SavedFilters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/__tests__/Topics.spec.tsx
Labels: scope/frontend

#2941 fixed unchecking the already checked Topics from main checkbox is not…
  kafka-ui-react-app/src/components/common/NewTable/SelectRowHeader.tsx
Labels: scope/frontend

#2702 Documentation for pluggable serdes
  README.md
  documentation/guides/Serialization.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ClusterSerdes.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ProducerRecordCreator.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdeInstance.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/DeserializationService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerdeTest.java
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/DeserializeResult.java
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/PropertyResolver.java
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/SchemaDescription.java
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/Serde.java
Labels: type/documentation, scope/backend

#2815 Topic creation: lock page until creation request finished
  kafka-ui-react-app/src/components/Topics/New/New.tsx
Labels: type/bug, scope/frontend

#2980 Excluding serde doc urls from URL check
  .github/workflows/documentation.yaml
Labels: scope/infrastructure

#2850 Data masking
  .github/workflows/documentation.yaml
  documentation/guides/DataMasking.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/DataMasking.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Mask.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/MaskingPolicy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Remove.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Replace.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/DataMaskingTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/MaskTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/RemoveTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/ReplaceTest.java
Labels: scope/backend, type/feature

#2989 Serdes improvements and fixes
  documentation/compose/kafka-ui-serdes.yaml
  documentation/compose/proto/key-types.proto
  documentation/compose/proto/values.proto
  documentation/guides/Protobuf.md
  documentation/guides/Serialization.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/BuiltInSerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ClusterSerdes.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdeInstance.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int32Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/StringSerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt32Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UuidBinarySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/DeserializationService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/SerdesInitializerTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
Labels: type/bug, type/enhancement, scope/backend
