Repository provectus/kafka-ui, pull requests merged in 2022-05, with the labels that each got.

#1898 Improve live tailing.
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts
  kafka-ui-react-app/src/components/common/MultiSelect/__test__/MultiSelect.styled.spec.tsx
  kafka-ui-react-app/src/components/common/Search/Search.tsx
Labels: type/enhancement, scope/frontend

#1908 Fix test warnings
  kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx
Labels: scope/frontend

#1832 Persist show internal topics switch state
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
Labels: type/enhancement, scope/frontend

#1904 Fix seek type select styles
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/enhancement, scope/frontend

#1900 Refetch topics list to display the updated data
  kafka-ui-react-app/src/components/Topics/List/List.tsx
Labels: type/bug, scope/frontend

#1899 Show confirmation modal when clear messages is clicked in topics list
  kafka-ui-react-app/src/components/Topics/List/List.tsx
Labels: type/bug, scope/frontend

#1896 Display a human-readable error message for topic custom parameters value
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/frontend

#1901 Fix topic messages partitions filter bug
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#1919 issues/1402. Fixed error message on incompatible schema
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/SchemaCompatibilityException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
Labels: type/bug, scope/backend

#1913 add endpoints of actuator/health in auth_whitelist
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AbstractAuthSecurityConfig.java
Labels: type/bug, scope/backend, status/accepted

#1924 Security / chore(dep): upgrade aws-msk-iam dependency due to log4j vulnerability
  kafka-ui-api/pom.xml
Labels: scope/backend, type/security, type/dependencies

#1925 Configure jacoco reports to sonar
  kafka-ui-api/pom.xml
Labels: scope/backend, scope/infrastructure

#1948 Issues/215 topics page tests
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicsTableCells.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.styled.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Messages.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/Settings.styled.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/validateMessage.spec.ts
  kafka-ui-react-app/src/components/Topics/Topic/__tests__/Topic.spec.tsx
  kafka-ui-react-app/src/components/Topics/__tests__/Topics.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.styled.tsx
  kafka-ui-react-app/src/redux/reducers/topics/__test__/fixtures.ts
Labels: scope/frontend, type/chore

#1920 In Sync Replicas metric displays correct information
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx
Labels: type/bug, scope/frontend

#1950 Romove enzyme. Cleanup warnings
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Alerts/Alert.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Nav/ClusterTab/__tests__/ClusterTab.styled.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/redux/interfaces/alerts.ts
  kafka-ui-react-app/src/redux/reducers/alerts/alertsSlice.ts
  kafka-ui-react-app/src/setupTests.ts
Labels: scope/frontend

#1958 Use Node v16.15.0
  kafka-ui-react-app/.nvmrc
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  pom.xml
Labels: scope/backend, scope/frontend, type/chore, type/dependencies

#1902 Refactor TopicMessages's store to redux/toolkit
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/DetailsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/FiltersContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/OverviewContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/TopicContainer.tsx
  kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts
  kafka-ui-react-app/src/redux/actions/__test__/thunks/topics.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/reducer.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
Labels: scope/frontend, type/refactoring

#1805 [issue 949] move dto mappers to controllers
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SchemaRegistryPaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
Labels: scope/backend, type/refactoring, type/chore

#1959 Added fixed width to the tables cells
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
Labels: type/bug, scope/frontend

#1981 Set indicator pane gap width according to figma
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
Labels: scope/frontend, type/chore

#1985 Border radius fixed
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#1964 Spinner fixed
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx
Labels: type/bug, scope/frontend

#1831 Added failed connections counter
  kafka-ui-react-app/src/components/Connect/List/List.tsx
  kafka-ui-react-app/src/components/Connect/List/ListContainer.ts
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/redux/reducers/connect/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/connect/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/selectors.ts
Labels: type/enhancement, good first issue, scope/frontend

#1952 1865 implement a tooltip with smart filters documentation
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/InfoModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/InfoModal.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/QuestionIcon.tsx
Labels: type/enhancement, scope/frontend

#1989 1865 implement a tooltip with smart filters documentation
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/InfoModal.tsx
Labels: type/bug, scope/frontend

#1993 Added replicas data to topic overview page
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
Labels: type/enhancement, scope/frontend

#1934 ISSUE-1024: BackwardRecordEmitter fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
Labels: type/bug, scope/backend, status/feature_testing

#2002 Feature/1334 please add a counters of all connectors tasks and failed connectors tasks
  kafka-ui-react-app/src/components/Connect/List/List.tsx
  kafka-ui-react-app/src/components/Connect/List/ListContainer.ts
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/redux/reducers/connect/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/selectors.ts
Labels: type/enhancement, scope/frontend

#1939 Refactoring Topics reducer into redux toolkit
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Alerts/Alerts.tsx
  kafka-ui-react-app/src/components/Alerts/__tests__/Alerts.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroupsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/DetailsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/Settings.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/SettingsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZoneContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/EditContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/Topics/Topic/TopicContainer.tsx
  kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts
  kafka-ui-react-app/src/redux/actions/__test__/thunks/topics.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/index.ts
  kafka-ui-react-app/src/redux/actions/thunks/index.ts
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/interfaces/alerts.ts
  kafka-ui-react-app/src/redux/interfaces/index.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
  kafka-ui-react-app/src/redux/reducers/alerts/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/alerts/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/alerts/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/alerts/reducer.ts
  kafka-ui-react-app/src/redux/reducers/alerts/selectors.ts
  kafka-ui-react-app/src/redux/reducers/alerts/utils.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/loader/reducer.ts
  kafka-ui-react-app/src/redux/reducers/loader/selectors.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
  kafka-ui-react-app/src/redux/store/configureStore/mockStoreCreator.ts
Labels: scope/frontend, type/refactoring, type/chore

#1999 Topics sorted alphabetically
  kafka-ui-react-app/src/components/Connect/List/ListContainer.ts
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/InfoModal.tsx
  kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
  kafka-ui-react-app/src/redux/reducers/connect/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/connect/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/selectors.ts
Labels: type/bug, scope/frontend

#2017 Click function moved from icon to row
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.tsx
  kafka-ui-react-app/src/components/common/Dropdown/DropdownItem.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#2027 Edit messages consumed text
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: scope/frontend, type/chore

#2041 issues/2037: Changed 'Connects' to 'Connectors'
  kafka-ui-react-app/src/components/Connect/List/List.tsx
Labels: scope/frontend, type/chore

#2044 Fix version display
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  pom.xml
Labels: scope/backend, scope/frontend, type/chore

#2034 Show close icon on hover
  kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts
Labels: good first issue, scope/frontend

#2029 The result of Clear Messages is not displayed in Topic overview
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
Labels: type/bug, good first issue, scope/frontend

#2028 fixing dropdown arrow behavior for Topics Messages
  kafka-ui-react-app/src/components/common/Icons/DropdownArrowIcon.tsx
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, good first issue, scope/frontend

#2036 Next button removed
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/lib/constants.ts
Labels: type/bug, scope/frontend

#2042 Fixed Selected partitions label
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/utils.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/utils.spec.ts
Labels: type/bug, scope/frontend

#2038 adding success alert for partitions update and display changes immedi…
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
Labels: type/bug, scope/frontend

#2033 adding error message when created message has wrong header format
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
Labels: type/bug, good first issue, scope/frontend

#2047 Error message about Value field requiredness is shown once the Custom Parameter added within Create a new Topic form
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/frontend

#2049 Fix the error messages about fields requiredness within Create a new Topic form
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: good first issue, scope/frontend

#2077 disable produce message button if cluster is readOnly
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
Labels: type/enhancement, scope/frontend
