Repository provectus/kafka-ui, pull requests merged in 2022-04, with the labels that each got.

#1789 Get Rid of Zookeeper
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/redux/actions/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/interfaces/broker.ts
  kafka-ui-react-app/src/redux/reducers/brokers/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/brokers/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/brokers/brokersSlice.ts
  kafka-ui-react-app/src/redux/reducers/brokers/selectors.ts
Labels: type/enhancement, scope/frontend

#1798 Add rimraf in dev-dependencies and remove from dependencies
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
Labels: scope/frontend, type/chore

#1781 ISSUE-1744: Fix search for messages with timestamp
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#1802 Issues/921 pagination consumer groups
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListContainer.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
Labels: type/enhancement, scope/frontend

#1774 Issues/1740 live tailing improvements
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Messages.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/contexts/TopicMessagesContext.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/src/redux/reducers/topicMessages/reducer.ts
Labels: type/enhancement, scope/frontend

#1729 Address issue #1699 (config option to deserialize proto message keys)
  .github/workflows/documentation.yaml
  documentation/guides/Protobuf.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDeTest.java
Labels: type/enhancement, scope/backend

#1717 Frontend: Restart connectors buttons
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/ActionsContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
  kafka-ui-react-app/src/redux/actions/__test__/thunks/connectors.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/connectors.ts
Labels: type/bug, scope/frontend

#1754 Kafka Connect: Implement basic auth
  README.md
  documentation/compose/jaas/kafka_connect.jaas
  documentation/compose/jaas/kafka_connect.password
  documentation/compose/kafka-ui-connectors-auth.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KafkaConnectClients.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaConnectCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-connect-api.yaml
Labels: type/enhancement, scope/backend, status/accepted

#1810 Added maxWidth to the table row styles
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
Labels: status/accepted

#1823 Fix page reset after search in topics list
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
Labels: type/bug, scope/frontend

#1834 Add a disclaimer
  README.md
Labels: type/documentation, status/accepted

#1833 exclude serviceWorker file from sonar's list
  kafka-ui-react-app/sonar-project.properties
Labels: status/accepted, type/chore

#1824 Issues/1740 live tailing order
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/reducer.ts
Labels: type/enhancement, scope/frontend, status/feature_testing

#1836 Fixing AdminClients requesting stucking
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
Labels: type/bug, scope/backend, status/accepted

#1814 Smart filters improvements
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddEditFilterContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/EditFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/SavedFilters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/SavedFilters.spec.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/__test__/ConfirmationModal.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/SavedIcon.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useModal.spec.ts
  kafka-ui-react-app/src/lib/hooks/useModal.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend

#1851 Remove unnecessary links and texts in topic messages
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
Labels: scope/frontend, type/regression

#1866 Added clearing offset
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#1829 Fix topic list invisible actions menu
  kafka-ui-react-app/src/components/Topics/List/List.styled.ts
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
Labels: type/bug, scope/frontend, type/regression

#1839 adding clear message if connector with new name already exists
  kafka-ui-react-app/src/redux/actions/__test__/thunks/connectors.spec.ts
  kafka-ui-react-app/src/redux/actions/thunks/connectors.ts
Labels: type/bug, good first issue, scope/frontend

#1758 Fix #1752
  README.md
  documentation/guides/SECURE_BROKER.md
Labels: type/documentation

#1874 Fix empty base path when forwarding to index page
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java
Labels: type/bug, scope/backend

#1872 Fix schema name nullability on compatibility change
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: type/bug, scope/backend, type/regression

#1843 Change spelling of ksqlDB at bread crumbs
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx
  kafka-ui-react-app/src/lib/__test__/paths.spec.ts
  kafka-ui-react-app/src/lib/constants.ts
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/bug, good first issue, scope/frontend

#1867 Hardcoded string with dropdown removed
  kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx
Labels: type/bug, scope/frontend

#1869 Auto-closing of alert message removed
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
Labels: type/bug, scope/frontend

#1849 Fix topic messages offset filter bug
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#1838 Fix topic messages old data persistence
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/Topics/Topic/TopicContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__tests__/Topic.spec.tsx
Labels: type/bug, scope/frontend

#1859 Fix topic custom parameter duplication overriding
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx
Labels: type/bug, scope/frontend

#1870 Fix double topic message display bug
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
Labels: type/bug, scope/frontend

#1876 Remove offset input render condition in topic messages filters
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Messages.spec.tsx
Labels: type/bug, scope/frontend

#1875 Fix dropdown jump effect bug on mouse over in topics list
  kafka-ui-react-app/src/components/Topics/List/List.styled.ts
  kafka-ui-react-app/src/components/Topics/List/List.tsx
Labels: type/bug, scope/frontend

#1821 fixing timestamp type for message content
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
Labels: good first issue, scope/frontend

#1812 Fixed tags width and added scroll to the table
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
  kafka-ui-react-app/src/components/common/table/Table/Table.styled.ts
Labels: type/bug, type/enhancement, good first issue, scope/frontend, status/feature_testing

#1848 Add Debounce to the Topics Filters search component
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Labels: type/enhancement, scope/frontend

#1825 Сlone topic functionality (FE)
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topics.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/enhancement, scope/frontend

#1864 Improve tests coverage
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
Labels: scope/frontend, type/chore

#1903 Smart filter improvements
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
Labels: type/enhancement, scope/frontend

#1883 Transform redux connect reducer and actions into toolkit slice.
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/ActionsContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/ConfigContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/Config.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Details.tsx
  kafka-ui-react-app/src/components/Connect/Details/DetailsContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItemContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/TasksContainer.ts
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/Tasks.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/Edit/EditContainer.ts
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/List.tsx
  kafka-ui-react-app/src/components/Connect/List/ListContainer.ts
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/Connect/New/NewContainer.ts
  kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/lib/testHelpers.tsx
  kafka-ui-react-app/src/redux/actions/__test__/thunks/connectors.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/connectors.ts
  kafka-ui-react-app/src/redux/actions/thunks/index.ts
  kafka-ui-react-app/src/redux/reducers/connect/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/connect/connectSlice.ts
  kafka-ui-react-app/src/redux/reducers/connect/reducer.ts
  kafka-ui-react-app/src/redux/reducers/connect/selectors.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
Labels: scope/frontend, type/refactoring, type/chore

#1826 fixing sonar code smells
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItemContainer.ts
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamsContainer.tsx
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
Labels: scope/frontend

#1906 Fix sonar badges in readme
  kafka-ui-react-app/README.md
Labels: type/documentation, status/accepted

#1868 Implement code highlighting for smart filters
  kafka-ui-react-app/README.md
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItemContainer.ts
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddEditFilterContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamsContainer.tsx
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
Labels: scope/frontend, type/feature
