Repository provectus/kafka-ui, pull requests merged in 2022-03, with the labels that each got.

#1672 live message tailing
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Select/LiveIcon.styled.tsx
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx
  kafka-ui-react-app/src/components/common/Select/__tests__/__snapshots__/Select.spec.tsx.snap
Labels: good first issue, status/feature_testing

#1658 Issues/1184
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/__tests__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/__tests__/Connect.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/__test__/KsqlDb.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/__test__/__snapshots__/KsqlDb.spec.tsx.snap
  kafka-ui-react-app/src/components/Nav/Nav.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx
  kafka-ui-react-app/src/lib/__test__/paths.spec.ts
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/bug, good first issue, scope/frontend

#1694 Topic existence check added to MessagesService to prevent accidental …
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractBaseTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
Labels: type/bug, scope/backend, status/accepted

#1639 Fix external resources loading for backend part
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AbstractAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AuthController.java
  kafka-ui-api/src/main/resources/static/static/css/bootstrap.min.css
  kafka-ui-api/src/main/resources/static/static/css/signin.css
Labels: type/enhancement, scope/backend

#1479 Ksql sse refactor
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlGrammar.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend, status/feature_testing

#1708 Update frontend to reflect design changes
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/__tests__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.styled.ts
  kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Icons/MessageToggleIcon.styled.ts
  kafka-ui-react-app/src/components/common/Icons/MessageToggleIcon.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: good first issue

#1711 Integration tests minor improvements
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/ReadOnlyModeTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/LogDirsTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-api/src/test/resources/application-test.yml
Labels: scope/backend, type/refactoring

#1716 Update stale workflow
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: scope/infrastructure

#1712 Adding Test File for Settings Component
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/Settings.spec.tsx
Labels: scope/frontend, status/feature_testing

#1574 Issues/1472 Added protection to prevent infinite loops when connection is in error with zookeeper
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ZookeeperServiceTest.java
Labels: type/bug, scope/backend, status/accepted

#1677 Issue 1650: improving test cases for ConsumerGroups components
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/__test__/TopicContents.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
Labels: type/enhancement, scope/frontend, status/accepted

#1664 Bump dependencies
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDeTest.java
  pom.xml
Labels: scope/backend, type/security

#1483 [FIX ISSUE-886] add failover support for Schema Registry
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/FailoverUrlList.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalSchemaRegistry.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/model/FailoverUrlListTest.java
Labels: type/bug, scope/backend

#1631 [ISSUE-1013]Clone topic functionality
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, status/accepted

#1693 Issue 1193: fixes empty pages for connect and connectors routes in Kafka Connect
  kafka-ui-react-app/src/components/Connect/Connect.tsx
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/bug, scope/frontend

#1688 Smart filters
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddEditFilterContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/EditFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/FilterModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.styled.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/feature

#1703 Reusable tables
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/TopicsTableCells.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
  kafka-ui-react-app/src/custom.d.ts
  kafka-ui-react-app/src/lib/__test__/propertyLookup.spec.ts
  kafka-ui-react-app/src/lib/hooks/useTableState.ts
  kafka-ui-react-app/src/lib/propertyLookup.ts
Labels: type/enhancement, scope/frontend, type/refactoring

#1576 [FE] KSQL execution is unstable
  kafka-ui-react-app/.eslintrc.json
  kafka-ui-react-app/sonar-project.properties
  kafka-ui-react-app/src/components/Connect/Details/__tests__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/ResultRenderer.styled.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/ResultRenderer.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/ResultRenderer.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/__snapshots__/ResultRenderer.spec.tsx.snap
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.styled.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/__test__/TableRenderer.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.styled.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx
  kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.styled.ts
  kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.tsx
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/PageHeading/PageHeading.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/SQLEditor.tsx
  kafka-ui-react-app/src/components/common/heading/Heading.styled.tsx
  kafka-ui-react-app/src/components/common/table/TableTitle/TableTitle.styled.tsx
  kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/__snapshots__/reducer.spec.ts.snap
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend

#1734 Adding Loader indicator to the TopicsConsumerGroups
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroupsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/__test__/TopicConsumerGroups.spec.tsx
  kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Labels: type/enhancement, scope/frontend

#1660 [Issue-998] Add Recreate topic button in to list of Topic and Details topic Overview
  kafka-ui-react-app/src/components/Topics/List/List.tsx
  kafka-ui-react-app/src/components/Topics/List/ListContainer.ts
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/DetailsContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/redux/actions/__test__/thunks/topics.spec.ts
  kafka-ui-react-app/src/redux/actions/actions.ts
  kafka-ui-react-app/src/redux/actions/thunks/topics.ts
  kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
Labels: scope/frontend, type/feature

#1745 Issues/1710 404 page navigating to routes manually
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/__tests__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/__tests__/Connect.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/KsqlDb/__test__/KsqlDb.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/__test__/__snapshots__/KsqlDb.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx
  kafka-ui-react-app/src/lib/__test__/paths.spec.ts
  kafka-ui-react-app/src/lib/paths.ts
Labels: type/bug, scope/frontend, type/regression

#1726 Get rid of zookeeper
  .github/workflows/documentation.yaml
  README.md
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/kafka-ui-zookeeper-ssl.yml
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ZooKeeperException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ZookeeperServiceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: type/enhancement, scope/backend, type/chore

#1747 Issues/1525 add sort order consumer group page
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ConsumerGroupsTableCells.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListContainer.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ConsumerGroupsTableCells.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
  kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
  kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx
  kafka-ui-react-app/src/components/common/table/Table/TableKeyLink.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/__test__/TableHeaderCell.styled.spec.tsx
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/consumerGroupSlice.spec.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
Labels: type/enhancement, scope/frontend

#1759 ISSUE-1613: Fix Topic not found error after new topic creation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
Labels: type/bug, scope/backend

#1746 add loading indicator to topic settings tab
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/Settings.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/Settings.spec.tsx
Labels: type/enhancement, scope/frontend

#1785 [CHORE] Unified getTagColor method
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/Utils/TagColor.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ConsumerGroupsTableCells.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Utils/TagColor.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/common/Tag/getTagColor.ts
Labels: scope/frontend, type/chore

#1770 Rename 'send' button to 'submit'
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
Labels: scope/frontend, type/chore

#1787 Clusters Style change during initializing phase + implement tests suites
  kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.styled.ts
  kafka-ui-react-app/src/components/Nav/ClusterTab/__tests__/ClusterTab.styled.spec.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend
