Repository provectus/kafka-ui, pull requests merged in 2022-12, with the labels that each got.

#2997 Serde autoconfiguration fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
Labels: type/bug, scope/backend

#3001 ISSUE-2968: Deleting a config parameter of topic doesn't take effect
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
Labels: type/bug, scope/backend

#2900 "Select filter" button is active without selecting any saved filter w…
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/SavedFilters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/SavedFilters.spec.tsx
Labels: type/bug, scope/frontend

#2999 [Infra]: Fix terraform deploy
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#2984 [KSQL] Implement mTLS configuration
  README.md
  documentation/compose/kafka-ssl-components.yaml
  documentation/compose/ssl/kafka.keystore.jks
  documentation/compose/ssl/kafka.truststore.jks
  documentation/compose/ssl/san.cnf
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalKsqlServer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
Labels: type/enhancement, scope/backend

#2981 Implement per-cluster polling rates limits
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ConsumingStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/DeserializationService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ConsumerRecordsUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/PollingThrottler.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/PollingThrottlerTest.java
Labels: scope/backend, type/feature

#3030 [BE] Fix a case when controller is not found
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
Labels: type/bug, scope/backend

#2895 chore: changed `dateFormat` for Timestamp value
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: scope/frontend, type/chore

#2970 KSQL: Focus onto query field after incorrect query execution
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
Labels: scope/frontend, type/chore

#2952 #2802 Create connector button is unavailable until the 2nd click
  kafka-ui-react-app/src/components/Connect/New/New.tsx
Labels: type/bug, scope/frontend

#2903 UI now showing broker list when DISABLELOGDIRSCOLLECTION=true
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
Labels: type/bug, type/enhancement, scope/frontend

#2966 Implement 404/403s on FE
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Connect.tsx
  kafka-ui-react-app/src/components/ErrorPage/ErrorPage.styled.ts
  kafka-ui-react-app/src/components/ErrorPage/ErrorPage.tsx
  kafka-ui-react-app/src/components/ErrorPage/__tests__/ErrorPage.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topics.tsx
  kafka-ui-react-app/src/components/common/SuspenseQueryComponent/SuspenseQueryComponent.tsx
  kafka-ui-react-app/src/components/common/SuspenseQueryComponent/__test__/SuspenseQueryComponent.spec.tsx
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend

#2950 Implement a workflow to prepare helm charts release
  .github/workflows/create-branch-for-helm.yaml
  .github/workflows/release.yaml
Labels: scope/infrastructure

#3050 Serde-api release adjustments
  kafka-ui-api/pom.xml
  kafka-ui-serde-api/pom.xml
  pom.xml
  settings.xml
Labels: scope/backend, type/chore, scope/infrastructure

#3054 [Chore] Fix serde api javadoc generation
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/PropertyResolver.java
  kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/Serde.java
Labels: scope/backend, type/chore

#2828 issue/UI support for MSK
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Topic.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/suite/topics/TopicsTests.java
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__test__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/topicParamsTransformer.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetain.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
  kafka-ui-react-app/src/lib/yupExtended.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
Labels: type/enhancement, scope/frontend, status/feature_testing

#2786 Add an indicator for an active broker controller
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.styled.ts
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/common/Icons/CheckMarkRoundIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/StarIcon.tsx
Labels: scope/frontend, status/feature_testing

#2743 Brokers API improvements
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalBroker.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Metrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/MetricsCollector.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/WellKnownMetricsTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.styled.ts
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/common/Icons/CheckMarkRoundIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/StarIcon.tsx
Labels: type/enhancement, scope/backend, type/refactoring

#3067 [FE] Fix cleanup policy submit/display
  kafka-ui-react-app/src/components/Topics/Topic/Edit/topicParamsTransformer.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Labels: type/bug, scope/frontend

#2862 Messages V1 Pagination
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Messages.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
Labels: type/bug, scope/frontend, type/regression

#3119 [FE] Change message timestamp format
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Indicators/Total.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
  kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
  kafka-ui-react-app/src/lib/fixtures/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/__tests__/dateTimeHelpers.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/timeFormat.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/useTimeFormat.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#3113 Drop experimental endpoints
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/InfoController.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Indicators/Total.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
  kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
  kafka-ui-react-app/src/lib/api.ts
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
  kafka-ui-react-app/src/lib/fixtures/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/__tests__/dateTimeHelpers.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/timeFormat.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
  kafka-ui-react-app/src/lib/hooks/useTimeFormat.ts
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: scope/backend, type/chore

#3131 fix helm release
  .github/workflows/release.yaml
Labels: status/triage

#3133 release 0.4.7
  charts/kafka-ui/Chart.yaml
Labels: scope/k8s

#3085 Fix/argo cd
  .github/workflows/separate_env_public_create.yml
Labels: scope/infrastructure

#3122 fix serde api versioning
  .github/workflows/release-serde-api.yaml
Labels: status/triage

#3134 fix tag
  .github/workflows/separate_env_public_create.yml
Labels: status/triage

#3139 [Helm] Update spring config location var name
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/deployment.yaml
Labels: scope/k8s

#3158 Post allure reports to s3 instead of a branch
  .github/workflows/e2e-checks.yaml
Labels: scope/infrastructure

#3159 [e2e] [infra] Fix allure reports s3 upload condition
  .github/workflows/e2e-checks.yaml
Labels: scope/infrastructure

#3160 [e2e] Update BaseTest with removing redundant data
  kafka-ui-e2e-checks/.env.example
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/NaviSideBar.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/services/ApiService.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/BaseSource.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Config.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Facade.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Setup.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/suite/connectors/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/suite/schemas/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/suite/topics/TopicMessagesTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/suite/topics/TopicsTests.java
Labels: scope/AQA

#3157 Bug: UnsupportedVersionException: includeClusterAuthorizedOperations
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
Labels: type/bug, scope/backend

#3062 Upgarde to Vite v4
  kafka-ui-react-app/jest.config.ts
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Schemas/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Messages.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__test__/Topic.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/globalCss.ts
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, status/feature_testing
