Repository provectus/kafka-ui, pull requests merged in 2022-01, with the labels that each got.

#1358 bytesOutPerSec metric added to topic
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
Labels: type/bug, scope/backend, status/accepted

#1351 Example for Azure AD setup
  guides/SSO.md
Labels: type/documentation

#1341 Design review fix
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/__snapshots__/Edit.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/New/__tests__/__snapshots__/New.spec.tsx.snap
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.styled.ts
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.styled.ts
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.styled.ts
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/__snapshots__/DangerZone.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.styled.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetain.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.styled.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/common/Button/Button.styled.ts
  kafka-ui-react-app/src/components/common/Pagination/PageControl.tsx
  kafka-ui-react-app/src/components/common/Pagination/Pagination.styled.ts
  kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/PageControl.spec.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/Pagination.spec.tsx
  kafka-ui-react-app/src/components/common/Pagination/__tests__/__snapshots__/PageControl.spec.tsx.snap
  kafka-ui-react-app/src/theme/index.scss
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, type/enhancement, scope/frontend, status/accepted, redesign

#1370 Support for ingressClassName in helm chart
  charts/kafka-ui/templates/ingress.yaml
  charts/kafka-ui/values.yaml
Labels: helm

#1372 Documentation/gifs
  README.md
  images/Create_message_kafka-ui.gif
  images/Create_topic_kafka-ui.gif
Labels: type/documentation

#1373 Create yaml-description.md
  guides/yaml-description.md
Labels: type/documentation

#1374 Documentation/yaml description
  README.md
  images/Create_schema.gif
  images/Interface.gif
Labels: type/documentation

#1371 Empty table for brokers & chnge tag styles
  kafka-ui-react-app/src/components/Brokers/Brokers.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.styled.ts
  kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
Labels: type/enhancement, scope/frontend, redesign

#1377 Documentation/new gifs
  README.md
  images/Connector_Topic_Consumer.gif
  images/Schema_Topic.gif
  images/apache-kafka-ui-interface-dashboard.png
Labels: type/documentation

#1318 Consumer groups pagination (Backend)
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#1376 Added GlobalSchemaSelector tests
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Select/Select.tsx
Labels: scope/frontend, scope/QA

#1396 Implement a workflow to create separate environment
  .github/workflows/separate_env_public_create.yml
  .github/workflows/separate_env_public_remove.yml
Labels: scope/infrastructure, type/feature

#1364 Added readonly status for the cluster.
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, type/regression

#1409 Fix small typo with 'offsets' in UI
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
Labels: type/bug, scope/frontend

#1389 [Fixes #1212] Confusing sorting UI in Topics
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx
  kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, redesign

#1416 Update triage configuration
  .github/workflows/triage_issues.yml
  .github/workflows/triage_prs.yml
Labels: scope/infrastructure

#1411 fixing empty screen issue when opening edit schema for proto type
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
Labels: type/bug, scope/frontend, redesign

#1401 tmp volume declaration removed
  kafka-ui-api/Dockerfile
Labels: type/enhancement, scope/backend

#1417 An action preventing merge with specific labels
  .github/workflows/block_merge.yml
Labels: scope/infrastructure

#1384 clusters"s table styles was fixed, added hyphens to breadcrumbs, URP …
  kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.styled.ts
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/LatestVersionItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
  kafka-ui-react-app/src/components/common/JSONViewer/JSONViewer.tsx
  kafka-ui-react-app/src/components/common/JSONViewer/StyledWrapper.styled.ts
  kafka-ui-react-app/src/components/common/JSONViewer/__test__/JSONViewer.spec.tsx
Labels: type/bug, scope/frontend

#1407 Updated toolkit and redux versions
  kafka-ui-react-app/package-lock.json
  kafka-ui-react-app/package.json
Labels: scope/frontend, type/dependencies

#1413 Fix schema versions order
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
Labels: type/bug, scope/frontend, status/accepted

#1395 [Fixes #1213] Topic Creation: Inconsistency in Deleted parameters
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.styled.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParams.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/IconButtonWrapper.ts
Labels: type/bug, scope/frontend, redesign

#1422 [Fixes #1391] Incorrect topic message content type (avro -> json)
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
Labels: type/bug, scope/frontend

#1427 Prepare bulma for removal
  kafka-ui-react-app/src/theme/index.scss
Labels: scope/frontend, type/chore

#1426 Protobuf schema is not formatted properly
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/Config.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Config/__test__/__snapshots__/Config.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/__snapshots__/Edit.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/__snapshots__/New.spec.tsx.snap
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx
  kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/LatestVersionItem.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/SchemaVersion.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/LatestVersionItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/common/Editor/Editor.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/StyledWrapper.styled.ts
  kafka-ui-react-app/src/components/common/EditorViewer/__test__/EditorViewer.spec.tsx
  kafka-ui-react-app/src/components/common/JSONEditor/JSONEditor.tsx
  kafka-ui-react-app/src/components/common/JSONViewer/JSONViewer.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/__tests__/SQLEditor.spec.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/__tests__/__snapshots__/SQLEditor.spec.tsx.snap
Labels: type/bug, type/enhancement, scope/frontend, redesign

#1429 [Resolves #1221] Unclear parameters for Consumers` Search. Inconsistency of Search line on Consumers page.
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
Labels: type/enhancement, scope/frontend, redesign

#1430 Issues/1217
  kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Connect/Edit/__tests__/__snapshots__/Edit.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/New/New.styled.ts
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/__snapshots__/New.spec.tsx.snap
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/frontend, redesign

#1397 Bugfix/select
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/common/Form/Form.styled.ts
  kafka-ui-react-app/src/components/common/Select/LiveIcon.styled.tsx
  kafka-ui-react-app/src/components/common/Select/Select.styled.ts
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/components/common/Select/__tests__/__snapshots__/Select.spec.tsx.snap
  kafka-ui-react-app/src/lib/hooks/useClickOutside.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, status/feature_testing

#1436 [Fixes #1428] Improve Sonar Cloud security hotspots metrics
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/Version/__tests__/__snapshots__/Version.spec.tsx.snap
  kafka-ui-react-app/src/components/Version/__tests__/compareVersions.spec.ts
  kafka-ui-react-app/src/components/Version/compareVersions.ts
  kafka-ui-react-app/src/redux/reducers/alerts/reducer.ts
  kafka-ui-react-app/src/redux/reducers/loader/reducer.ts
Labels: type/bug, scope/frontend

#1434 Change the way of release workflow
  .github/release_drafter.yaml
  .github/workflows/branch-deploy.yml
  .github/workflows/master.yaml
  .github/workflows/release.yaml
  .github/workflows/release_drafter.yml
  kafka-ui-api/pom.xml
  kafka-ui-contract/pom.xml
  kafka-ui-e2e-checks/pom.xml
  pom.xml
Labels: scope/infrastructure

#1445 ISSUE-1444: Additional params added to connector restart endpoint to be able to…
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-connect-api.yaml
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap
Labels: type/bug, scope/backend

#1450 fix missing pathType in ingress.yaml for kube cluster version 1.22+
  charts/kafka-ui/templates/ingress.yaml
Labels: type/bug, scope/k8s

#1467 fixing cannot create a topic issue,added some default values to pass …
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Labels: type/bug, scope/frontend, type/regression

#1394 Fixed breadcrumbs params detection
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Connect/Connect.tsx
  kafka-ui-react-app/src/components/Connect/__tests__/__snapshots__/Connect.spec.tsx.snap
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
  kafka-ui-react-app/src/components/KsqlDb/KsqlDb.tsx
  kafka-ui-react-app/src/components/Schemas/Schemas.tsx
  kafka-ui-react-app/src/components/Topics/Topics.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/FormBreadcrumbs.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.context.ts
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.provider.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.route.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx
  kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx
Labels: scope/frontend, type/chore

#1475 replacing enzyme with react testing library for topics overview
  kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
Labels: type/enhancement, scope/frontend, status/accepted

#1474 Schema type is not updated when history push #1469
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
Labels: type/bug, scope/frontend

#1478 required PR checks workflows adaptation
  .github/workflows/backend.yml
  .github/workflows/documentation.yaml
  .github/workflows/e2e-checks.yaml
  .github/workflows/frontend.yaml
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/infrastructure

#1486 Specify time period in which custom deployment will be available
  .github/workflows/branch-deploy.yml
Labels: type/chore, scope/infrastructure

#1484 Limit codeql run by frontend paths
  .github/workflows/codeql-analysis.yml
Labels: type/enhancement, scope/infrastructure

#1495 Add helm chart testing workflow
  .github/workflows/helm.yaml
Labels: scope/infrastructure

#1505 Add step to attach built jar to a release
  .github/workflows/release.yaml
Labels: scope/infrastructure

#1506 Add missing readonly field
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
Labels: type/bug, scope/backend, type/regression

#1403 add admin auth and search filter for ldap
  docker/auth-ldap.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
Labels: type/enhancement, scope/backend, status/accepted

#1507 [Fixes #1412] UI: Invalid button title on Connector Tasks page
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/__tests__/__snapshots__/ListItem.spec.tsx.snap
Labels: type/bug, scope/frontend

#1522 Add schedule for running helm workflow
  .github/workflows/helm.yaml
Labels: type/enhancement, scope/infrastructure, scope/k8s

#1367 [ISSUE-1191, ISSUE-1208] Implemented search and pagination for schema…
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SchemaRegistryPaginationTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/Schemas/Details/Details.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/LatestVersionItem.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/SchemaVersion.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/LatestVersionItem.spec.tsx.snap
  kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/SchemaVersion.spec.tsx.snap
  kafka-ui-react-app/src/components/Schemas/Details/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/fixtures.ts
  kafka-ui-react-app/src/components/Schemas/Schemas.tsx
  kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx
  kafka-ui-react-app/src/components/common/Search/Search.tsx
  kafka-ui-react-app/src/lib/hooks/useSearch.ts
  kafka-ui-react-app/src/redux/reducers/schemas/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts
Labels: type/enhancement, scope/backend, scope/frontend, impact/api

#1494 [ISSUE 1408] Get rid of Bulma's classes 'Elements'.
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap
  kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
  kafka-ui-react-app/src/components/KsqlDb/Query/ResultRenderer.styled.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/ResultRenderer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.styled.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamAction.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamButton.tsx
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/common/Icons/WarningIcon.tsx
  kafka-ui-react-app/src/components/common/table/SortableCulumnHeader/SortableColumnHeader.tsx
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
  kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/__snapshots__/SortableColumnHeader.spec.tsx.snap
  kafka-ui-react-app/src/theme/bulma_overrides.scss
  kafka-ui-react-app/src/theme/index.scss
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/refactoring
