Repository provectus/kafka-ui, pull requests merged in 2022-10, with the labels that each got.

#2687 Renamed "total partitions" to "partitions"
  kafka-ui-react-app/src/components/Topics/List/TopicTable.tsx
Labels: scope/frontend, type/chore

#2692 Add scrollable wrapper to the new table component
  kafka-ui-react-app/src/components/App.styled.ts
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.styled.ts
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/InputCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, status/feature_testing

#2666 fixed tests connectors buttons with a sandwich menu #2403
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
Labels: scope/frontend, type/chore, status/feature_testing

#2696 Minor backend fixes
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerdeTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend, type/chore

#2698 [e2e] Rename POM classes according to their type and naming on UI
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/KafkaConnectList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/ProduceMessagePanel.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Facade.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/QA

#2662 Add "Total size" of Partition within Topic's statistics #2536
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
Labels: scope/frontend, type/chore, status/feature_testing

#2190 Support prometheus as a metrics interface
  README.md
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/auth-ldap.yaml
  documentation/compose/e2e-tests.yaml
  documentation/compose/jmx-exporter/kafka-broker.yml
  documentation/compose/jmx-exporter/kafka-prepare-and-run
  documentation/compose/kafka-ui-auth-context.yaml
  documentation/compose/kafka-ui-connectors-auth.yaml
  documentation/compose/kafka-ui-jmx-secured.yml
  documentation/compose/kafka-ui-with-jmx-exporter.yaml
  documentation/compose/kafka-ui.yaml
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/BrokerMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Metrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/MetricsConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Statistics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStatisticsScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsCache.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxMetricsFormatter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxMetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/MetricsCollector.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/MetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusEndpointMetricsParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/RawMetric.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxMetricsName.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxMetricsValueName.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/NumberUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/producer/KafkaTestProducer.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/JmxMetricsFormatterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/PrometheusEndpointMetricsParserTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetrieverTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/WellKnownMetricsTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/NumberUtilTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: scope/backend, type/feature

#2637 Unify tabs placement
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/QaseExtension.java
  kafka-ui-react-app/src/components/Connect/Details/DetailsPage.tsx
  kafka-ui-react-app/src/components/Connect/Details/__tests__/DetailsPage.spec.tsx
Labels: scope/frontend, type/refactoring, status/feature_testing

#2689 #2325 Make connectors table rows clickable and #2076 Implement connec…
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/KafkaConnectList.java
  kafka-ui-react-app/src/components/Connect/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Connect/List/List.styled.ts
  kafka-ui-react-app/src/components/Connect/List/List.tsx
  kafka-ui-react-app/src/components/Connect/List/ListItem.tsx
  kafka-ui-react-app/src/components/Connect/List/RunningTasksCell.tsx
  kafka-ui-react-app/src/components/Connect/List/TopicsCell.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#2694 Migrate Dashboard table to the new version on table components #2682
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClusterName.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/List.tsx
  kafka-ui-react-app/src/components/common/NewTable/LinkCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
Labels: scope/frontend, type/refactoring

#2737 Msk serverless support (BE)
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/TopicMetadataException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/feature

#2732 Smart filter offset binding
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessageFilters.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/MessageFiltersTest.java
Labels: type/bug, scope/backend, impact/documentation

#2632 Add workflows for helm release
  .github/workflows/helm.yaml
  .github/workflows/release-helm.yaml
Labels: scope/infrastructure

#2291 Implement Connectors sorting
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#2765 Renamed content to value
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
Labels: scope/frontend, type/chore

#2704 Migrate Topic Overview to the new version of table #2684
  kafka-ui-react-app/src/components/Topics/Topic/Overview/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
Labels: scope/frontend, type/refactoring

#2717 2681 migrate topic consumers page to new version of table component
  kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
Labels: scope/frontend, type/refactoring

#2736 [e2e] refactor POM classes structure
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/NaviSideBar.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorCreateForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/KafkaConnectList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/ProduceMessagePanel.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Setup.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
Labels: scope/AQA

#2744 Fix error with empty fields in Stream properties
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
Labels: type/bug, scope/frontend

#2750 Fix helm charts validation
  .github/workflows/helm.yaml
Labels: scope/infrastructure

#2793 Bump version of mockito up to 4.8.1
  kafka-ui-api/pom.xml
  pom.xml
Labels: scope/backend, type/dependencies

#2806 Update Groovy version up to 3.0.13
  pom.xml
Labels: scope/backend, type/dependencies

#2729 Emitters logic refactoring
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/OffsetsInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/SeekOperations.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ConsumerPosition.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekBackward.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekForward.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/OffsetsInfoTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/SeekOperationsTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/OffsetsSeekTest.java
Labels: scope/backend, type/refactoring

#2796 ISSUE-1994: Deprecated ksq apis removed
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KsqlClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KsqlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/BaseStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/CreateStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/DescribeStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/DropStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/ExplainStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/SelectStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/TerminateStrategy.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KsqlServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/CreateStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/DescribeStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/DropStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/ExplainStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/SelectStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategyTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/strategy/ksql/statement/TerminateStrategyTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/chore

#2809 fix openTopic() method to wait element
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/KafkaConnectList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
Labels: type/bug, scope/AQA

#2797 fix helm.yaml
  .github/workflows/helm.yaml
Labels: scope/infrastructure

#2782 Wrong actuator path with custom 2758
  kafka-ui-react-app/src/lib/hooks/api/actuatorInfo.ts
Labels: type/bug, scope/frontend

#2799 Removed @types/yup package updated yup version to 0.32.11
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
Labels: scope/frontend, type/dependencies

#2766 [UI] Topic search not working properly with pagination #2705
  kafka-ui-react-app/src/components/common/Search/Search.tsx
Labels: type/bug, scope/frontend

#2804 fix: ksql request input overflow
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
Labels: type/bug, scope/frontend

#2821 change app version in charts.yaml
  .github/workflows/helm.yaml
  charts/kafka-ui/Chart.yaml
Labels: scope/infrastructure, scope/k8s

#2812 Changed Content to Value and Update a Test
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/__tests__/MessageContent.spec.tsx
Labels: scope/frontend, type/chore

#2741 Testing library update to 14.4.3
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Brokers/Broker/BrokerLogdir/__test__/BrokerLogdir.spec.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/__test__/Configs.spec.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/Tasks.spec.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/__test__/KsqlDbItem.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenu.spec.tsx
  kafka-ui-react-app/src/components/Nav/__tests__/Nav.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/SchemaVersion.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Edit/__tests__/Edit.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx
  kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/Schemas/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/ListPage.spec.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/__test__/DangerZone.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/AddFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/InfoModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/SavedFilters.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/__tests__/MessageContent.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Messages.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/Metrics.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__test__/Topic.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParamField.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__test__/CustomParams.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TimeToRetainBtn.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
  kafka-ui-react-app/src/components/__tests__/App.spec.tsx
  kafka-ui-react-app/src/components/common/Alert/__tests__/Alert.spec.tsx
  kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
  kafka-ui-react-app/src/components/common/Search/__tests__/Search.spec.tsx
  kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx
  kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx
Labels: scope/frontend, type/dependencies

#2826 fix release-heml.yaml
  .github/workflows/release-helm.yaml
Labels: scope/infrastructure

#2830 Bump netty version
  kafka-ui-e2e-checks/pom.xml
Labels: scope/backend, type/dependencies

#2837 #1362. Drop deprecated method
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/chore

#2831 adding checksum for config from values
  charts/kafka-ui/templates/deployment.yaml
Labels: type/enhancement, scope/k8s

#2835 Make topic bulk actions buttons always visible
  kafka-ui-react-app/src/components/Topics/List/BatchActionsBar.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
Labels: type/enhancement, scope/frontend

#2841 Fix the Brokers' test file fixtures, mock data to correspond the correct type
  kafka-ui-react-app/src/components/Brokers/utils/__test__/fixtures.ts
Labels: type/bug, scope/frontend, hacktoberfest-accepted

#2843 ReadMe modification to include Vite.
  kafka-ui-react-app/README.md
Labels: type/documentation, scope/frontend

#2788 ISSUE-2787: Setting default config values properly
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopicConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaConstants.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#2846 Fix topic internal indication
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
Labels: type/bug, scope/backend, status/feature_testing, hacktoberfest-accepted

#2777 Upgrade kafka in compose files (#2601)
  docker-compose.md
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/auth-ldap.yaml
  documentation/compose/e2e-tests.yaml
  documentation/compose/kafka-cluster-sr-auth.yaml
  documentation/compose/kafka-clusters-only.yaml
  documentation/compose/kafka-ssl.yml
  documentation/compose/kafka-ui-arm64.yaml
  documentation/compose/kafka-ui-auth-context.yaml
  documentation/compose/kafka-ui-connectors-auth.yaml
  documentation/compose/kafka-ui-jmx-secured.yml
  documentation/compose/kafka-ui-sasl.yaml
  documentation/compose/kafka-ui-with-jmx-exporter.yaml
  documentation/compose/kafka-ui.yaml
  documentation/compose/kafka-with-zookeeper.yaml
  documentation/compose/scripts/clusterID
  documentation/compose/scripts/create_cluster_id.sh
  documentation/compose/scripts/update_run_cluster.sh
  documentation/guides/SSO.md
Labels: type/documentation, hacktoberfest-accepted

#2847 Add a separate endpoint for frontend time format
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/InfoController.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/lib/hooks/api/__tests__/timeFormat.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
Labels: type/bug, scope/backend, scope/frontend, hacktoberfest-accepted

#2781 ISSUE-2103: Fixing AdminClient timeout on listOffsets
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalPartition.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
Labels: type/bug, scope/backend

#2832 feat(schema-registry): Implement schema-registry mTLS configuration
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalSchemaRegistry.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/SecuredWebClient.java
Labels: type/enhancement, scope/backend
