Repository provectus/kafka-ui, pull requests merged in 2023-02, with the labels that each got.

#2887 Display In Sync Replicas (ISR) by Partition on Topic overview
  kafka-ui-react-app/src/components/Topics/Topic/Overview/Overview.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Overview/Overview.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend

#3028 Fix json paths in previews
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/PreviewModal.styled.ts
Labels: scope/frontend, type/chore, status/feature_testing

#3294 wizard kafka cluster validate
  kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/Wizard/schema.ts
Labels: scope/frontend

#3286 Wizard schema registry
  kafka-ui-react-app/src/components/Wizard/WizardForm/SchemaRegistry/SchemaRegistry.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
Labels: scope/frontend, status/feature_testing

#3264 App configuration validation endpoint
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaClusterValidator.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: status/triage

#3242 Application config API
  documentation/compose/kafka-ui.yaml
  kafka-ui-api/Dockerfile
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/KafkaUiApplication.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthPropertiesConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/logout/CognitoLogoutSuccessHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AccessController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ValidationException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/AccessContext.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Resource.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ApplicationConfigAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/DataMasking.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Mask.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/MaskingPolicy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Replace.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ApplicationRestarter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaClusterValidator.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaVersion.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/MapUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/PollingThrottler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/DynamicConfigOperationsTest.java
  kafka-ui-contract/pom.xml
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: status/accepted

#3311 refactor Registry Form
  kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/SchemaRegistry/SchemaRegistry.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/Wizard/schema.ts
Labels: scope/frontend

#3310 [BE] SR: maxInMemorySize property setting added to SR client
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
Labels: type/bug, scope/backend

#3303 Wizard JMX Metrics form
  kafka-ui-react-app/src/components/Wizard/WizardForm/Metrics/Metrics.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/Wizard/schema.ts
  kafka-ui-react-app/src/lib/constants.ts
Labels: scope/frontend

#3300 Wizard Kafka Connect form
  kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaConnect/KafkaConnect.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/common/Input/InputLabel.styled.ts
Labels: scope/frontend

#3336 Per-cluster SSL verification settings
  README.md
  documentation/compose/kafka-ssl-components.yaml
  documentation/compose/kafka-ui-serdes.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaClusterValidator.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/SslPropertiesUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#3341 Using JRE instead of JDK in docker image construction
  kafka-ui-api/Dockerfile
Labels: type/enhancement, scope/backend

#3314 Extend testcase with a recursive reference
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
Labels: scope/backend, type/chore

#3266 Avro (Embedded) serde implementation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/AvroEmbeddedSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/AvroEmbeddedSerdeTest.java
Labels: type/enhancement, scope/backend

#3376 ISSUE-1452: Auth errors suppressing
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
Labels: type/bug, type/enhancement, scope/backend

#3391 Wizard: Application info API
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ClusterFeature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Statistics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#3197 FE: Redesign connector actions
  kafka-ui-react-app/src/components/Connect/Details/Actions/Action.styled.ts
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  kafka-ui-react-app/src/components/common/Button/Button.styled.ts
  kafka-ui-react-app/src/components/common/Icons/ChevronDownIcon.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend

#3377 ISSUE-3288 : Ksql select header's response parsing improved, tests added
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/response/ResponseParserTest.java
Labels: type/bug, scope/backend

#2986 #2963 Topic - new topic: Focus is not set to the 'Topic name' field after "Add a new Topic" button is pressed
  kafka-ui-react-app/src/components/Connect/New/New.tsx
  kafka-ui-react-app/src/components/Schemas/New/New.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Labels: scope/frontend, type/chore, status/feature_testing
