Repository provectus/kafka-ui, pull requests merged in 2023-07, with the labels that each got.

#3986 Infra: Fix image build for non OCI-compliant runtimes
  .github/workflows/master.yaml
Labels: scope/infrastructure

#4009 FE: Consumers: Replace zero consumer lag with "N/A"
  kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
Labels: scope/frontend, type/chore

#4008 FE: Fix Messages: Produce: "Keep contents" not re-generated
  kafka-ui-react-app/src/components/Topics/Topic/Messages/getDefaultSerdeName.ts
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/utils.ts
Labels: type/bug, scope/frontend

#4003 CVE fixes, 07.23
  kafka-ui-api/pom.xml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlApiClientTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java
  pom.xml
Labels: scope/backend, type/security

#3747 SchemaRegistry references support
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaSrMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/SchemaReferencesResolver.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/AvroExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/DataSetFieldsExtractors.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/JsonSchemaExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/ProtoExtractor.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/SchemaReferencesResolverTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/AvroExtractorTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/JsonSchemaExtractorTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/ProtoExtractorTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-sr-api.yaml
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#4043 Infra: tighten github_token security
  .github/workflows/backend.yml
  .github/workflows/e2e-checks.yaml
  .github/workflows/frontend.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/welcome-first-time-contributors.yml
Labels: scope/infrastructure

#4042 BE: Respect system proxy settings in WebClient
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
Labels: type/enhancement, scope/backend

#4058 Error message from SR propagation
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Labels: scope/backend, type/chore
