Repository provectus/kafka-ui, pull requests merged in 2023-09, with the labels that each got.

#4090 FE: Fix dateTimeHelpers.spec.ts linter error
  kafka-ui-react-app/src/lib/hooks/__tests__/dateTimeHelpers.spec.ts
Labels: scope/frontend, type/chore

#4177 Common prefix for all application metrics
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ApplicationMetrics.java
Labels: type/enhancement, scope/backend

#4207 Fix persistent installation link in README
  README.md
Labels: type/documentation, status/accepted

#4227 Bump Spring Boot version to 3.1.3
  pom.xml
Labels: scope/backend, type/security, type/dependencies
