Repository provectus/kafka-ui, pull requests merged in 2023-08, with the labels that each got.

#4063 BE: Serde tiny improvements and fixes
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/AvroEmbeddedSerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Base64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UuidBinarySerde.java
Labels: scope/backend, type/refactoring

#4061 BE: KC: Suppress unavailable connects
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaConnectMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporterTest.java
Labels: type/bug, scope/backend

#3783 BE: Impl ACL endpoints for consumer, producer, stream apps
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AclsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/acl/AclsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/acl/AclsServiceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#4034 ISSUE-3820: ACL enablement check fixes:
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
Labels: type/bug, scope/backend

#4069 ISSSUE-4052: Polling metrics
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AbstractAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ConsumingStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/EmptyPollsCounter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/EnhancedConsumer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessagesProcessing.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/PolledRecords.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/PollingThrottler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ApplicationMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ConsumerRecordsUtil.java
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
Labels: scope/backend, type/feature

#4033 BE: RBAC: Fix unknown resource exception
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
Labels: type/bug, scope/backend, area/rbac

#4045 FE: Logout button link is bound to a wrong div
  kafka-ui-react-app/src/components/NavBar/UserInfo/UserInfo.tsx
  kafka-ui-react-app/src/components/NavBar/UserInfo/__tests__/UserInfo.spec.tsx
Labels: type/bug, scope/frontend

#4078 BE: RBAC: Skip rbac checks in case of app config
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
Labels: type/bug, scope/backend, area/rbac

#4064 BE: Audit: Minor refactoring
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditWriter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditServiceTest.java
Labels: type/enhancement, scope/backend

#4002 Throw obvious exception in case no oauth2 providers have been defined
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/condition/CognitoCondition.java
Labels: scope/backend, type/chore

#3866 FE: display consumerGroupID in Reset Offsets page
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/Form.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
Labels: scope/frontend, status/accepted, type/chore

#4084 Make the container timezone configurable
  kafka-ui-api/Dockerfile
Labels: scope/infrastructure

#4092 FE: Update topic deletion disabled message
  kafka-ui-react-app/src/components/Topics/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
Labels: scope/frontend, type/chore

#4098 Infra: Fix frontend sonar jdk warning
  .github/workflows/frontend.yaml
Labels: scope/infrastructure

#4093 RBAC: Implement roles by github teams
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
Labels: type/enhancement, scope/backend, status/image_testing, area/rbac

#4041 Add protobuf raw message deserializer
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufRawSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufRawSerdeTest.java
Labels: type/enhancement, scope/backend

#4103 BE: Implement audit log level
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AclAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ApplicationConfigAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AuditAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ClusterConfigAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConnectAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConsumerGroupAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/KsqlAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/PermissibleAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/SchemaAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/TopicAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditRecord.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditWriter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditWriterTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#4128 FE: Refactor RBAC tests, fix "subset" permissions issues
  kafka-ui-react-app/src/components/common/ActionComponent/__tests__/fixtures.ts
  kafka-ui-react-app/src/lib/__test__/permission.spec.ts
  kafka-ui-react-app/src/lib/permissions.ts
Labels: type/bug, scope/frontend, type/refactoring

#4135 BE: Use HTTP GET for basic auth
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
Labels: type/bug, scope/backend, area/auth

#4138 BE: Audit: consider RBAC might be disabled
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java
Labels: type/bug, scope/backend, area/audit

#4140 BE: Minor restart logic refactoring
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
Labels: scope/backend, type/refactoring

#4097 FE: Topics: Do not send properties which are not defined explicitly
  kafka-ui-react-app/src/components/Topics/New/New.tsx
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
  kafka-ui-react-app/src/redux/interfaces/topic.ts
Labels: type/bug, scope/frontend

#3969 FE: Topics: Minor fixes for Create Topic form
  kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.styled.ts
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: scope/frontend, type/chore

#3804 FE: Broker: Config: Implement search by the Value
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/brokers/BrokersConfigTab.java
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
Labels: type/enhancement, scope/frontend

#4146 FE: Bump node & pnpm versions
  .github/workflows/frontend.yaml
  kafka-ui-react-app/.nvmrc
  kafka-ui-react-app/package.json
  pom.xml
Labels: scope/frontend, dependencies

#4085 FE: Fix active controller badge on invalid node
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/CheckMarkRoundIcon.tsx
  kafka-ui-react-app/src/lib/fixtures/brokers.ts
  kafka-ui-react-app/src/lib/fixtures/clusters.ts
Labels: type/bug, scope/frontend, status/pre-merge

#4123 Topic analysis improvement: Updated style for percentage of completion.
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Statistics/Statistics.styles.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend

#3971 Fix sonar code issues
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/WebclientProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AuthenticatedUser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/RbacOAuth2User.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/RbacOidcUser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AccessController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/OffsetsInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/DescribeLogDirsMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalLogDirStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/AccessContext.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Base64Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ConsumerOffsetsSerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int32Serde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversion.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverter.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Schema.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicCreateEditForm.java
Labels: scope/backend, type/chore, scope/AQA, status/pre-merge

#4171 BE: Fix cognito roles extractor regression
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
Labels: type/bug, scope/backend

#4121 Topic active producer's states retrieval API
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#4116 BE: Refactor SchemaRegistry serialization logic
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/AvroSchemaRegistrySerializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/JsonSchemaSchemaRegistrySerializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/ProtobufSchemaRegistrySerializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/Serialize.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/annotation/KafkaClientInternalsDependant.java
Labels: scope/backend, type/refactoring
