Repository provectus/kafka-ui, pull requests merged in 2023-06, with the labels that each got.

#3899 Fix typo in persistent installation
  README.md
Labels: type/documentation

#3779 Implementation Message data digits are rounded #3751
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#3891 RBAC: Fix KC restart permissions
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx
  kafka-ui-react-app/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx
  kafka-ui-react-app/src/components/Connect/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Connect/New/New.tsx
Labels: type/bug, scope/backend, scope/frontend

#3861 Infra: Fix image build for non OCI-compliant envs
  .github/workflows/release.yaml
Labels: type/bug, scope/infrastructure

#3906 Update openapi dependency (#3034)
  pom.xml
Labels: scope/backend, dependencies

#3808 BE: Impl support for Avro logical types
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/JsonToAvroConversionException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/AvroSchemaRegistrySerializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/MessageFormatter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversion.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerdeTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversionTest.java
Labels: type/enhancement, scope/backend

#3937 ISSUE-3916: not failing on null-valued connector's configs values
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
Labels: type/bug, scope/backend

#3655 FE: Redirect the user to the wizard page
  kafka-ui-react-app/src/components/PageContainer/PageContainer.tsx
  kafka-ui-react-app/src/components/PageContainer/__tests__/PageContainer.spec.tsx
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: type/bug, scope/frontend

#3941 FE: Refactor theme selection mechanism
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/NavBar/NavBar.tsx
  kafka-ui-react-app/src/components/PageContainer/PageContainer.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/SQLEditor.tsx
  kafka-ui-react-app/src/components/contexts/ThemeModeContext.tsx
  kafka-ui-react-app/src/index.tsx
Labels: type/bug, scope/frontend, area/ux

#3934 FE: Wizard: Fix keytab param and boolean params quoting
  kafka-ui-react-app/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts
  kafka-ui-react-app/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
Labels: type/bug, scope/frontend, status/image_testing

#3898 FE: fix dropdown on topics (issue#3896)
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
Labels: type/bug, scope/frontend

#3889 Infra: post links as checks, not comments
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  .github/workflows/build-public-image.yml
Labels: scope/infrastructure

#3917 Infra: Release workflow: Call charts action in another repo
  .github/workflows/release.yaml
Labels: scope/infrastructure

#3935 FE: Disable resetting offsets for unassigned CGs
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
Labels: type/bug, scope/frontend

#3915 FE: Fix reach query not initiating requests for local host
  kafka-ui-react-app/src/components/App.tsx
Labels: type/bug, scope/frontend

#3946 BE: RBAC: Fix viewable topics filter
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java
Labels: type/bug, scope/backend, area/rbac

#3923 3110: Fixed Timestamp issue on clearall function click
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#3795 Helm: Add loadBalancerIP attribute for LB svc
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/service.yaml
  charts/kafka-ui/values.yaml
Labels: type/enhancement, scope/k8s

#3951 Nuke helm charts
  .github/workflows/create-branch-for-helm.yaml
  .github/workflows/helm.yaml
  .github/workflows/release-helm.yaml
  charts/kafka-ui/.helmignore
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/README.md
  charts/kafka-ui/index.yaml
  charts/kafka-ui/templates/NOTES.txt
  charts/kafka-ui/templates/_helpers.tpl
  charts/kafka-ui/templates/configmap.yaml
  charts/kafka-ui/templates/configmap_fromValues.yaml
  charts/kafka-ui/templates/deployment.yaml
  charts/kafka-ui/templates/hpa.yaml
  charts/kafka-ui/templates/ingress.yaml
  charts/kafka-ui/templates/networkpolicy-egress.yaml
  charts/kafka-ui/templates/networkpolicy-ingress.yaml
  charts/kafka-ui/templates/secret.yaml
  charts/kafka-ui/templates/service.yaml
  charts/kafka-ui/templates/serviceaccount.yaml
  charts/kafka-ui/values.yaml
Labels: scope/infrastructure

#3952 Update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/helm.yml
Labels: scope/infrastructure

#3953 Infra: Revert comment action for published images
  .github/workflows/build-public-image.yml
  .github/workflows/delete-public-image.yml
Labels: scope/infrastructure

#3831 Audit backend
  documentation/compose/jmx-exporter/kafka-broker.yml
  documentation/compose/kafka-ui-arm64.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AclsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ClustersController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/AccessContext.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Resource.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AuditAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/PermissibleAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditRecord.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditWriter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SchemaRegistryPaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditServiceTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/feature, area/audit

#3656 BE: Implement Smart filters test execution endpoint
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, area/ux

#3825 BE: Chore: drop deprecated protobuf single file property. Issue 2893
  .gitignore
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
Labels: scope/backend, type/chore

#3962 FE: Add precision for disk usage
  kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx
  kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/common/NewTable/SizeCell.tsx
Labels: type/enhancement, scope/frontend, area/ux

#3931 BE: Skip FQ union types for avro-json convertions
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/JsonAvroConversionException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/JsonToAvroConversionException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversion.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversionTest.java
Labels: type/bug, scope/backend, area/serde

#3771 BE: Serde: Implement a serde for consumer_offsets topic
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ConsumerOffsetsSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ConsumerOffsetsSerdeTest.java
Labels: type/enhancement, scope/backend, area/serde

#3957 BE: Fix CORS once again
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java
Labels: type/bug, scope/backend, status/image_testing, area/auth

#3972 Checking Broker's config search is case insensetive
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/StringUtils.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/brokers/BrokersTest.java
Labels: scope/AQA

#3964 FE: Ignore expected 404 on topic statistics page
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
Labels: type/bug, scope/frontend, area/ux

#3979 Implement a RBAC authorities extractor to support subject-level role matching
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/RbacLdapAuthoritiesExtractor.java
Labels: type/bug, type/enhancement, scope/backend

#3980 ODD: Skipping topic exporting if we failed to load/parse topic's schema from SR
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddExporter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporter.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporterTest.java
Labels: type/bug, scope/backend

#3871 FE: CONSUMERS: Add a tooltip for a state
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
  kafka-ui-react-app/src/lib/constants.ts
Labels: scope/frontend, type/chore, area/consumers

#3995 FE: Add robots.txt
  kafka-ui-react-app/public/robots.txt
Labels: scope/frontend, type/security
