Repository provectus/kafka-ui, pull requests merged in 2023-03, with the labels that each got.

#3425 Wizard: Keystore separation
  README.md
  documentation/compose/kafka-ssl-components.yaml
  documentation/compose/kafka-ssl.yml
  documentation/compose/kafka-ui-arm64.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/MetricsConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaServicesValidation.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/SslPropertiesUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlApiClientTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, impact/changelog, impact/documentation

#3289 Integration with ODD
  kafka-ui-api/pom.xml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/ConnectorInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddExporter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddExporterScheduler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddIntegrationConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddIntegrationProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/Oddrn.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/AvroExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/DataSetFieldsExtractors.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/JsonSchemaExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/schema/ProtoExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/AvroExtractorTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/JsonSchemaExtractorTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/schema/ProtoExtractorTest.java
  pom.xml
Labels: scope/backend, type/feature

#3356 Brokers: fix missing tooltip for config source
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/common/ActionComponent/ActionComponent.ts
  kafka-ui-react-app/src/components/common/Tooltip/Tooltip.tsx
  kafka-ui-react-app/src/lib/hooks/useActionTooltip.ts
Labels: type/bug, scope/frontend

#3400 Fix number of partitions field validation issue
  kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
Labels: type/bug, scope/frontend

#3394 "Copy to clipboard" doesn't work #2819
  kafka-ui-react-app/src/components/common/Alert/Alert.styled.ts
  kafka-ui-react-app/src/components/common/Alert/Alert.tsx
  kafka-ui-react-app/src/lib/errorHandling.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx
  kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Labels: type/bug, scope/frontend, type/regression

#3005 [UI] Topics: Message tab Oldest first button overlaps the Submit
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
Labels: type/bug, scope/frontend, status/feature_testing

#3448 Wizard: Jmx ssl
  README.md
  documentation/compose/jaas/client.properties
  documentation/compose/jaas/kafka_connect.jaas
  documentation/compose/jaas/kafka_connect.password
  documentation/compose/jaas/kafka_server.conf
  documentation/compose/jaas/schema_registry.jaas
  documentation/compose/jaas/schema_registry.password
  documentation/compose/kafka-ui-jmx-secured.yml
  kafka-ui-api/Dockerfile
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/JmxConnectionInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxMetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxSslSocketFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxPoolFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/SslPropertiesUtil.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetrieverTest.java
Labels: type/enhancement, scope/backend

#3357 ProtobufFilesSerde imports implementation & refactoring
  documentation/compose/kafka-ui-serdes.yaml
  documentation/compose/proto/key-types.proto
  documentation/guides/Protobuf.md
  documentation/guides/Serialization.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
  kafka-ui-api/src/test/resources/protobuf-serde/address-book.proto
  kafka-ui-api/src/test/resources/protobuf-serde/lang-description.proto
  kafka-ui-api/src/test/resources/protobuf-serde/language/language.proto
  kafka-ui-api/src/test/resources/protobuf-serde/sensor.proto
Labels: type/bug, scope/backend

#3451 Helm: Add the `global.imageRegistry` parameter
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/_helpers.tpl
Labels: scope/k8s

#3471 [Helm] Release 0.6.0
  charts/kafka-ui/Chart.yaml
Labels: scope/k8s

#2773 Add message about not existing offline clusters in Dashboard (#2707)
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/__test__/BrokersList.spec.tsx
Labels: scope/frontend, type/chore

#3257 fix warnnings
  .github/workflows/aws_publisher.yaml
  .github/workflows/block_merge.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/delete-public-image.yml
  .github/workflows/e2e-checks.yaml
  .github/workflows/separate_env_public_create.yml
Labels: scope/infrastructure

#3480 get rid of Husky pre-commit hooks
  kafka-ui-react-app/.husky/pre-commit
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
Labels: scope/frontend, status/accepted, type/chore

#3383 Change Consumers Topic label position
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.styled.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/common/table/Table/TableKeyLink.styled.ts
Labels: scope/frontend, type/chore, status/feature_testing

#3412 "Saved filters" invalid font #3384
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
Labels: scope/frontend, type/chore

#3493 Fix typo (groups)
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/chore

#3080 The Message count is not updating with Clearing message for partition
  kafka-ui-react-app/src/components/Topics/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/List/BatchActionsBar.tsx
  kafka-ui-react-app/src/components/Topics/List/__tests__/TopicTable.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/ActionsCell.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__test__/Topic.spec.tsx
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/reducer.spec.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
Labels: type/bug, scope/frontend

#3497 [Infra] A first try of reusable workflows
  .github/workflows/branch-deploy.yml
  .github/workflows/build-template.yml
Labels: scope/infrastructure

#3505 Implement an internal topic name prefix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/topics/TopicsTest.java
Labels: type/bug, scope/backend

#3519 Revert "[Infra] A first try of reusable workflows"
  .github/workflows/branch-deploy.yml
  .github/workflows/build-template.yml
Labels: scope/infrastructure

#3513 Polling timeouts made configurable
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/EmptyPollsCounter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/PollingSettings.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/PollingThrottler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ResultSizeLimiter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/PollingThrottlerTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend

#3533 Upgrade aws creds action
  .github/workflows/aws_publisher.yaml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/delete-public-image.yml
  .github/workflows/e2e-automation.yml
  .github/workflows/e2e-checks.yaml
  .github/workflows/e2e-weekly.yml
  .github/workflows/separate_env_public_create.yml
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#3529 CORS configuration added
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java
Labels: scope/backend, type/chore, status/image_testing

#3478 Migrate KSQL to RQ. Get rid of redux reducer
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqlDb/KsqlQueryForm.java
  kafka-ui-react-app/src/components/App.tsx
  kafka-ui-react-app/src/components/KsqlDb/KsqlDb.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/KsqlDbItem.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/__test__/KsqlDbItem.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/KsqlDbItem/utils/ksqlRowData.ts
  kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
  kafka-ui-react-app/src/components/KsqlDb/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/__test__/Query.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.tsx
  kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/__test__/TableRenderer.spec.tsx
  kafka-ui-react-app/src/components/KsqlDb/TableView.tsx
  kafka-ui-react-app/src/components/KsqlDb/__test__/KsqlDb.spec.tsx
  kafka-ui-react-app/src/components/Schemas/Details/__test__/fixtures.ts
  kafka-ui-react-app/src/components/common/ActionComponent/__tests__/fixtures.ts
  kafka-ui-react-app/src/components/common/DiffViewer/DiffViewer.tsx
  kafka-ui-react-app/src/components/common/Editor/Editor.tsx
  kafka-ui-react-app/src/components/common/NewTable/TimestampCell copy.tsx
  kafka-ui-react-app/src/components/common/SQLEditor/SQLEditor.tsx
  kafka-ui-react-app/src/components/common/Tooltip/Tooltip.tsx
  kafka-ui-react-app/src/components/common/table/TableTitle/TableTitle.styled.tsx
  kafka-ui-react-app/src/lib/hooks/__tests__/fixtures.ts
  kafka-ui-react-app/src/lib/hooks/api/kafkaConnect.ts
  kafka-ui-react-app/src/lib/hooks/api/ksqlDb.tsx
  kafka-ui-react-app/src/lib/hooks/useMessageFiltersStore.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/lib/yupExtended.ts
  kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/fixtures.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/__test__/selectors.spec.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
  kafka-ui-react-app/src/redux/reducers/ksqlDb/selectors.ts
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, status/accepted, type/chore

#3508 Refactor Consumers Section
  kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/Form.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.styled.ts
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/__test__/TopicContents.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/ListItem.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/ListContainer.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/lib/fixtures/consumerGroups.ts
  kafka-ui-react-app/src/lib/hooks/api/consumers.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/redux/interfaces/consumerGroup.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/consumerGroupSlice.spec.ts
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
  kafka-ui-react-app/src/redux/reducers/index.ts
Labels: scope/frontend, type/chore, status/feature_testing

#3526 FE: Bugfix/wizard form validation
  kafka-ui-react-app/src/components/common/Select/ControlledSelect.tsx
  kafka-ui-react-app/src/components/common/Select/Select.tsx
  kafka-ui-react-app/src/widgets/ClusterConfigForm/index.tsx
Labels: type/bug, scope/frontend

#3555 Verify internal topics naming
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualSuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/topics/TopicsTest.java
Labels: scope/AQA

#3548 Topic deletion enabled for MSK Serverless
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
Labels: type/bug, scope/backend

#3551 improvement/config-save-spinner add spinner for submit button
  kafka-ui-react-app/src/components/common/Button/Button.tsx
  kafka-ui-react-app/src/components/common/Button/__tests__/Button.spec.tsx
  kafka-ui-react-app/src/components/common/PageLoader/PageLoader.styled.ts
  kafka-ui-react-app/src/components/common/PageLoader/PageLoader.tsx
  kafka-ui-react-app/src/components/common/Spinner/Spinner.styled.ts
  kafka-ui-react-app/src/components/common/Spinner/Spinner.tsx
  kafka-ui-react-app/src/components/common/Spinner/types.ts
  kafka-ui-react-app/src/widgets/ClusterConfigForm/index.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#3561 improvement/subject-name-display add subject name on schema edit form
  kafka-ui-react-app/src/components/Schemas/Edit/Form.tsx
Labels: scope/frontend, type/chore, status/feature_testing

#3392 update prerequisites readme file
  documentation/project/contributing/prerequisites.md
Labels: type/documentation

#3545 Fix UserInfoUri usage for Github Enterprise
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
  kafka-ui-api/src/main/resources/application-local.yml
Labels: type/bug, scope/backend

#3577 Update GitHub OAuth configuration for GitHub Enterprise Server
  configuration/authentication/oauth2.md
Labels: type/documentation

#3588 Hude documentation refactoring
  CONTRIBUTING.md
  README.md
  charts/kafka-ui/README.md
  documentation/guides/AWS_IAM.md
  documentation/guides/DataMasking.md
  documentation/guides/Protobuf.md
  documentation/guides/SASL_SCRAM.md
  documentation/guides/SECURE_BROKER.md
  documentation/guides/SSO.md
  documentation/guides/Serialization.md
  documentation/project/ROADMAP.md
  documentation/project/contributing/README.md
  documentation/project/contributing/building-and-running-without-docker.md
  documentation/project/contributing/building.md
  documentation/project/contributing/prerequisites.md
  documentation/project/contributing/set-up-git.md
  documentation/project/contributing/testing.md
  helm_chart.md
Labels: type/documentation, impact/documentation

#3585 FE: Fix topics unchecking w/ "Show Internal Topics"
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
Labels: type/bug, scope/frontend

#3579 Fix invalid font color for 404 w/ dark theme
  kafka-ui-react-app/src/components/ErrorPage/ErrorPage.styled.ts
Labels: scope/frontend, type/chore
