Repository provectus/kafka-ui, pull requests merged in 2023-01, with the labels that each got.

#3173 [Docs] Update JMX in kafka-ui.yaml
  documentation/compose/kafka-ui.yaml
Labels: type/documentation

#3038 [BE] Update tests for confluent platform 7+
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/container/KafkaConnectContainer.java
Labels: scope/backend, type/chore

#3185 Fix minor RBAC/auth NPEs, init null collections
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthPropertiesConverter.java
Labels: type/bug, scope/backend

#3106 [FE] Implement a full support for custom context path
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java
  kafka-ui-react-app/index.html
  kafka-ui-react-app/src/components/Cluster/Cluster.tsx
  kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
  kafka-ui-react-app/vite.config.ts
Labels: type/enhancement, scope/frontend

#3069 Implement healthcheck for e2e
  documentation/compose/e2e-tests.yaml
Labels: scope/infrastructure

#2908 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type/documentation, impact/documentation

#3192 [FE] Build fails after #2372
  kafka-ui-react-app/index.html
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/vite.config.ts
Labels: scope/frontend, type/chore

#3179 KafkaConnect & KsqlDb failover
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KafkaConnectClientsFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalKsqlServer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaConnectCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlApiClientTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java
Labels: scope/backend, type/refactoring

#3203 add Local browser VM option
  kafka-ui-e2e-checks/README.md
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/services/ApiService.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/BaseSource.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/configs/Config.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/configs/Profiles.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/drivers/LocalWebDriver.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
Labels: scope/AQA

#3199 remove classnames lib from the bundle
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
Labels: scope/frontend, type/chore

#3116 Deleting a consumer hangs the page
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts
Labels: type/bug, scope/frontend

#3189 [e2e] Fix allure url
  .github/workflows/e2e-checks.yaml
Labels: scope/infrastructure

#3145 Filters Fixing the seekTo parameter when all the partitions are selected
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#3223 fix withStartupTimeout()
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
Labels: scope/AQA

#3188 Consumer groups loading performance impr
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/MapUtil.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
Labels: type/bug, scope/backend

#3088 Proto to JsonSchema well-known types support
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/MessageFormatter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AnyFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/RefFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/SimpleJsonType.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
  kafka-ui-react-app/package.json
  kafka-ui-react-app/pnpm-lock.yaml
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/utils.ts
Labels: type/bug, scope/backend, scope/frontend

#3123 Implement SchemaRegistry openapi client
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/KafkaConnectClientsFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/SchemaCompatibilityException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/SchemaTypeNotSupportedException.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaSrMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/FailoverUrlList.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalKsqlServer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalSchemaRegistry.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaConnectCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/SecuredWebClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/model/FailoverUrlListTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SchemaRegistryPaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlApiClientTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/ReactiveFailoverTest.java
  kafka-ui-contract/pom.xml
  kafka-ui-contract/src/main/resources/swagger/kafka-sr-api.yaml
Labels: scope/backend, type/refactoring, type/chore

#3201 [BE] Impl basic auth for prometheus
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetrieverTest.java
Labels: type/enhancement, scope/backend

#3235 [BE] Fix Avro SR for non-TopicNameStrategy subjects
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerdeTest.java
Labels: type/bug, scope/backend

#3245 Wizard kafka cluster form
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/Authentication.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/Wizard/schema.ts
Labels: status/triage

#3246 Fix URL for Logout button
  kafka-ui-react-app/src/components/NavBar/UserInfo/UserInfo.tsx
  kafka-ui-react-app/src/components/NavBar/UserInfo/__tests__/UserInfo.spec.tsx
Labels: type/bug, scope/frontend

#3232 Change workflow names
  .github/workflows/backend.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  .github/workflows/create-branch-for-helm.yaml
  .github/workflows/documentation.yaml
  .github/workflows/e2e-checks.yaml
  .github/workflows/frontend.yaml
  .github/workflows/helm.yaml
  .github/workflows/master.yaml
  .github/workflows/release-serde-api.yaml
  .github/workflows/terraform-deploy.yml
Labels: scope/infrastructure

#3260 ConfigTest stats initializing added
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java
Labels: scope/backend, type/chore

#3259 Add variable for pathtype
  charts/kafka-ui/Chart.yaml
  charts/kafka-ui/templates/ingress.yaml
  charts/kafka-ui/values.yaml
Labels: scope/k8s

#3262 [BE] Suppressing failures when describe log dirs not supported
  README.md
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
Labels: type/enhancement, scope/backend

#3276 [BE] Fix case-sensitive search in broker's topics (Closes #3043)
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
Labels: type/bug, scope/backend

#3287 MessagesServiceTest:maskingAppliedOnConfiguredClusters fix
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
Labels: scope/backend, type/chore

#3268 Wizard authentication
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/Authentication.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/AuthenticationMethods.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/DelegationTokens.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/MTLS.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/SaslAwsIam.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/SaslGssapi.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/SaslJaas.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/SaslOauthbearer.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/AuthenticationMethods/UsernamePassword.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts
  kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx
  kafka-ui-react-app/src/components/Wizard/schema.ts
Labels: scope/frontend, status/feature_testing
