Repository provectus/kafka-ui, pull requests merged in 2023-04, with the labels that each got.

#3578 ErrorPage Number variable
  kafka-ui-react-app/src/components/ErrorPage/ErrorPage.styled.ts
  kafka-ui-react-app/src/components/ErrorPage/ErrorPage.tsx
Labels: scope/frontend, type/chore

#3591 HTTP 400 for clusters with special symbols
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/lib/hooks/api/ksqlDb.tsx
  kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
Labels: type/bug, scope/frontend

#3567 Fix dummy field in saved JSON message content
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
Labels: type/bug, scope/frontend

#3601 Fix Edit config: Selected text background color is transparent
  kafka-ui-react-app/src/components/common/Editor/Editor.tsx
  kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.styled.ts
Labels: scope/frontend, type/chore

#3594 Support for old ksql versions
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2.java
Labels: type/bug, scope/backend

#3602 Remove internet dependency / google fonts
  kafka-ui-react-app/index.html
  kafka-ui-react-app/public/fonts/Inter-Medium.ttf
  kafka-ui-react-app/public/fonts/Inter-Regular.ttf
  kafka-ui-react-app/public/fonts/RobotoMono-Medium.ttf
  kafka-ui-react-app/public/fonts/RobotoMono-Regular.ttf
Labels: type/enhancement, scope/frontend

#3616 Update without-docker.md
  development/building/without-docker.md
Labels: type/documentation

#3481 Redirect the user to the wizard page if no clusters
  kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
  kafka-ui-react-app/src/components/Dashboard/__test__/Dashboard.spec.tsx
  kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#3089 Add consumer search in Topic View #2538
  kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
Labels: type/enhancement, scope/frontend

#3609 [e2e] Selenoid setup for multithread
  .github/workflows/e2e-automation.yml
  .github/workflows/e2e-checks.yaml
  .github/workflows/e2e-weekly.yml
  documentation/compose/e2e-tests.yaml
  kafka-ui-e2e-checks/README.md
  kafka-ui-e2e-checks/docker/selenoid-git.yaml
  kafka-ui-e2e-checks/docker/selenoid-local.yaml
  kafka-ui-e2e-checks/pom.xml
  kafka-ui-e2e-checks/selenoid/config/browsersGit.json
  kafka-ui-e2e-checks/selenoid/config/browsersLocal.json
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/BasePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/panels/NaviSideBar.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicCreateEditForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicsList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/services/ApiService.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/BaseSource.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/drivers/LocalWebDriver.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/drivers/WebDriver.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/variables/Url.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/BaseTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/SmokeTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/ksqlDb/KsqlDbTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/topics/TopicsTest.java
  kafka-ui-e2e-checks/src/test/resources/manual.xml
  kafka-ui-e2e-checks/src/test/resources/qase.xml
  kafka-ui-e2e-checks/src/test/resources/regression.xml
  kafka-ui-e2e-checks/src/test/resources/sanity.xml
  kafka-ui-e2e-checks/src/test/resources/smoke.xml
Labels: type/enhancement, scope/infrastructure, scope/AQA

#3631 "Done" event sending fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ConsumingStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessageFilterStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessagesProcessing.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/TailingEmitter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
Labels: type/bug, scope/backend

#3628 Get rid of "Topic analysis successfully started" message
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
Labels: scope/frontend, type/chore

#3408 Display smart filters filtered stats #2680
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/FiltersContainer.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
  kafka-ui-react-app/src/redux/interfaces/topic.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/selectors.ts
  kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
Labels: type/enhancement, scope/frontend

#3603 Add devcontainer configuration file
  .devcontainer/devcontainer.json
Labels: type/chore, scope/infrastructure

#3624 ISSUE-3144: CVE fixes, Springboot upd
  kafka-ui-api/Dockerfile
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/client/RetryingKafkaConnectClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java
  kafka-ui-contract/pom.xml
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  pom.xml
Labels: scope/backend, type/security

#3570 BE: Opt out of version check
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ApplicationInfoService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/GithubReleaseInfoTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#3582 [FE] Messages filtering by offset & timestamp doesn't work
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: type/bug, scope/frontend

#3647 Exempt appconfig from rbac check
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
Labels: type/bug, scope/backend

#2599 SR: Display a warning in case of invalid syntax
  kafka-ui-react-app/src/components/Schemas/Edit/Form.tsx
  kafka-ui-react-app/src/lib/__test__/yupExtended.spec.ts
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/enhancement, scope/frontend

#3618 ISSUE-3416: ReactiveAdminClient::listOffsets() fix
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
Labels: type/bug, scope/backend, status/pre-merge

#3623 FE: Format field previews one per line
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Topic.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/ProduceMessagePanel.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/services/ApiService.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/connectors/ConnectorsTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/MessagesTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/TopicsTest.java
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
Labels: type/bug, scope/frontend, status/pre-merge

#3592 Topics: Messages: 404 with schema created by .NET containing guid
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/utils.ts
Labels: type/bug, scope/frontend, type/regression

#3608 It's possible to save the filters with the same name for Messages
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx
Labels: type/bug, scope/frontend

#3621 Consumers: Topic list: Implement sorting
  kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/TopicContents.tsx
Labels: type/enhancement, scope/frontend

#3661 FE: Fix config param source nullability
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
Labels: type/bug, scope/frontend

#3081 Marked serde-failed messages with red
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.styled.ts
  kafka-ui-react-app/src/components/common/Ellipsis/Ellipsis.styled.ts
  kafka-ui-react-app/src/components/common/Ellipsis/Ellipsis.tsx
  kafka-ui-react-app/src/components/common/Icons/WarningRedIcon.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend, status/pre-merge

#3667 [e2e] Clear entered queue check
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/BasePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlDbList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/ksqldb/KsqlDbTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/MessagesTest.java
  kafka-ui-e2e-checks/src/test/resources/regression.xml
  kafka-ui-e2e-checks/src/test/resources/sanity.xml
  kafka-ui-e2e-checks/src/test/resources/smoke.xml
Labels: scope/AQA

#3433 FE: KSQL: Implement sorting
  kafka-ui-react-app/src/components/KsqlDb/TableView.tsx
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
Labels: type/enhancement, scope/frontend, status/pre-merge

#3669 Infra: disable creating non-templated issues
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.md
Labels: scope/infrastructure

#3523 Config wizard BE: Add remaining cluster properties to wizard API
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/WebclientProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/chore, status/pre-merge

#3457 fix missing permission for recreate topic
  kafka-ui-react-app/src/components/Topics/List/ActionsCell.tsx
Labels: type/bug, scope/frontend, status/pre-merge

#3681 Bump helm version to 0.6.2
  charts/kafka-ui/Chart.yaml
Labels: scope/k8s

#3683 BE: Fix protobuf map support
  documentation/compose/proto/values.proto
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AnyFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ArrayFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/EnumJsonType.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/FieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonType.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/MapFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/OneOfFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/RefFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/SimpleFieldSchema.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/SimpleJsonType.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
Labels: type/bug, scope/backend

#3689 FE: Fix topic messages Invalid size for null key/value messages
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
Labels: type/bug, scope/frontend

#3633 Allow sorting consumer groups by topic num
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
Labels: type/enhancement, scope/backend, scope/frontend, status/pre-merge

#3685 BE: Make paging sizes configurable
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend

#3699 TSC error submit callback type
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx
Labels: scope/frontend

#3566 Broker partitions skew added to API
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalBroker.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/PartitionDistributionStats.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/model/PartitionDistributionStatsTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, status/pre-merge

#3660 Add KC quick actions into the sandwich menu
  kafka-ui-react-app/src/components/Connect/List/ActionsCell.tsx
  kafka-ui-react-app/src/components/Connect/List/__tests__/List.spec.tsx
  kafka-ui-react-app/src/components/common/Dropdown/Dropdown.styled.ts
  kafka-ui-react-app/src/lib/hooks/api/kafkaConnect.ts
Labels: type/enhancement, scope/frontend, status/feature_testing

#3687 Implement system redirects to Topics after topic delete #3044
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/Topics/Topic/__test__/Topic.spec.tsx
Labels: type/bug, scope/frontend

#3693 CVE fixes: spring-core(6.0.7), transitive org.json
  kafka-ui-api/pom.xml
  pom.xml
Labels: scope/backend, type/security

#3580 FE: Topics: Remove a success message upon creating a topic
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/TopicsTest.java
  kafka-ui-react-app/src/lib/hooks/api/topics.ts
Labels: scope/frontend, type/chore

#2854 Don't Dismiss Produce Message pane after Send
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.styled.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
  kafka-ui-react-app/src/components/common/SlidingSidebar/SlidingSidebar.styled.ts
Labels: type/enhancement, scope/frontend

#3719 Minor BE fixes and improvements
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ConsumerRecordDeserializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisStats.java
Labels: scope/backend, type/refactoring, type/chore

#3718 FE: Display message key/value serdes
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/__tests__/MessageContent.spec.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#3672 Implementation opt out of version check #2753
  kafka-ui-react-app/src/components/Version/Version.tsx
  kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
  kafka-ui-react-app/src/components/common/Icons/WarningIcon.tsx
  kafka-ui-react-app/src/lib/fixtures/actuatorInfo.ts
  kafka-ui-react-app/src/lib/fixtures/latestVersion.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/actuatorInfo.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/__tests__/latestVersion.spec.ts
  kafka-ui-react-app/src/lib/hooks/api/actuatorInfo.ts
  kafka-ui-react-app/src/lib/hooks/api/latestVersion.ts
Labels: type/enhancement, scope/frontend

#3700 RBAC: LDAP support
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/RbacLdapUser.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/condition/ActiveDirectoryCondition.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/LdapAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/RbacLdapAuthoritiesExtractor.java
Labels: type/enhancement, scope/backend, impact/changelog
