Repository provectus/kafka-ui, pull requests merged in 2023-05, with the labels that each got.

#3664 Masking "fieldsNamePattern" fields selection policy added
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/DataMasking.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/FieldsSelector.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Mask.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/MaskingPolicy.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Remove.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/masking/policies/Replace.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/FieldsSelectorTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/MaskTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/RemoveTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/masking/policies/ReplaceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/enhancement, scope/backend, impact/changelog

#3756 docs: update helm install way
  configuration/helm-charts/quick-start.md
Labels: type/documentation

#3698 Compare versions back button #3670
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.styled.ts
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.tsx
  kafka-ui-react-app/src/components/Schemas/Diff/__test__/Diff.spec.tsx
Labels: type/enhancement, scope/frontend, status/feature_testing

#3758 [e2e] Check Show Streams request execution
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/ksqldb/KsqlDbTest.java
Labels: scope/AQA

#3762 BE: Wizard: Fix file upload
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/controller/ApplicationConfigControllerTest.java
  kafka-ui-api/src/test/resources/fileForUploadTest.txt
  kafka-ui-contract/pom.xml
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, scope/backend

#2818 Expose cluster ACL list
  documentation/compose/jaas/kafka_server.conf
  documentation/compose/jaas/zookeeper_jaas.conf
  documentation/compose/kafka-ui-acl-with-zk.yaml
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AclsController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ClusterFeature.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/AccessContext.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Resource.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AclAction.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/acl/AclCsv.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/acl/AclsService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxSslSocketFactory.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaVersion.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/acl/AclCsvTest.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/acl/AclsServiceTest.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: scope/backend, type/feature

#3746 Implementation updating an existing schema with valid syntax #3739
  kafka-ui-react-app/src/components/Schemas/Edit/Form.tsx
  kafka-ui-react-app/src/lib/__test__/yupExtended.spec.ts
  kafka-ui-react-app/src/lib/yupExtended.ts
Labels: type/bug, scope/frontend, status/feature_testing

#3750 Implementation Connectors: no error is displayed in the syntax is not valid #3734
  kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx
Labels: type/bug, scope/frontend, status/feature_testing

#3787 [e2e] Stop query functionality check
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/ksqldb/KsqlDbTest.java
Labels: scope/AQA

#3634 Implementation add clear button to the search component #2686
  kafka-ui-react-app/src/components/common/Input/Input.styled.ts
  kafka-ui-react-app/src/components/common/Input/Input.tsx
  kafka-ui-react-app/src/components/common/Search/Search.tsx
  kafka-ui-react-app/src/components/common/Search/__tests__/Search.spec.tsx
Labels: scope/frontend, type/chore

#3786 Implementation Serde fallback icon: Add a tooltip #3716
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
Labels: scope/frontend, type/chore

#3785 Implementation Messages: Produce pane is too long #3738
  kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
Labels: scope/frontend, type/chore

#3684 Disable configure buttons if there are no permissions
  kafka-ui-react-app/src/components/Dashboard/ClusterTableActionsCell.tsx
  kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
Labels: type/bug, scope/frontend

#3715 Implementation Messages: UI displays nonsensical timestamps #3251
  kafka-ui-react-app/src/lib/dateTimeHelpers.ts
Labels: type/bug, scope/frontend

#3626 View broker skew in kafka-ui
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/PartitionDistributionStats.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/brokers/BrokersList.java
  kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
  kafka-ui-react-app/src/components/Brokers/BrokersList/SkewHeader/SkewHeader.styled.ts
  kafka-ui-react-app/src/components/Brokers/BrokersList/SkewHeader/SkewHeader.tsx
  kafka-ui-react-app/src/components/common/NewTable/ColoredCell.tsx
  kafka-ui-react-app/src/components/common/NewTable/SizeCell.tsx
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/enhancement, scope/frontend

#3767 Diff overlay of Avro schemas in comparision
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
  kafka-ui-react-app/src/components/Schemas/Diff/Diff.styled.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: type/bug, scope/frontend, type/regression

#3784 BE: Smart Filter: Setting key/value variable to original string when it cant be parsed as json
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessageFilters.java
  kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/MessageFiltersTest.java
Labels: type/bug, scope/backend

#3754 fixed:#3346
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java
  kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
Labels: type/bug, scope/frontend

#3721 Refactor toggle button
  kafka-ui-react-app/src/components/common/Switch/Switch.styled.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/refactoring

#3798 Revert "FE: Redirect the user to the wizard page if no clusters (#3481)"
  kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
  kafka-ui-react-app/src/components/Dashboard/__test__/Dashboard.spec.tsx
  kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
  kafka-ui-react-app/src/lib/testHelpers.tsx
Labels: status/triage

#3740 RBAC: Implement generic OAuth2 authority extractor
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthProperties.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthPropertiesConverter.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/logout/CognitoLogoutSuccessHandler.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/provider/Provider.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GoogleAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/OauthAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/ProviderAuthorityExtractor.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java
Labels: type/enhancement, scope/backend

#3764 BE: Update Kafka config-related info on schedule
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
Labels: type/enhancement, scope/backend

#3805 BE: RBAC: Implement restart permission for KC
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConnectAction.java
Labels: type/enhancement, scope/backend

#3662 FE: Expose cluster ACL list
  kafka-ui-react-app/src/components/ACLPage/ACLPage.tsx
  kafka-ui-react-app/src/components/ACLPage/List/List.styled.ts
  kafka-ui-react-app/src/components/ACLPage/List/List.tsx
  kafka-ui-react-app/src/components/ACLPage/List/__test__/List.spec.tsx
  kafka-ui-react-app/src/components/ClusterPage/ClusterPage.tsx
  kafka-ui-react-app/src/components/Nav/ClusterMenu.tsx
  kafka-ui-react-app/src/components/common/Button/Button.styled.ts
  kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx
  kafka-ui-react-app/src/components/common/Icons/DeleteIcon.tsx
  kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts
  kafka-ui-react-app/src/components/common/NewTable/Table.tsx
  kafka-ui-react-app/src/components/contexts/ConfirmContext.tsx
  kafka-ui-react-app/src/lib/api.ts
  kafka-ui-react-app/src/lib/fixtures/acls.ts
  kafka-ui-react-app/src/lib/hooks/api/acl.ts
  kafka-ui-react-app/src/lib/hooks/useConfirm.ts
  kafka-ui-react-app/src/lib/paths.ts
  kafka-ui-react-app/src/theme/theme.ts
Labels: scope/frontend, type/feature

#3778 Add OpenShift route Helm Chart parameters configuration
  configuration/helm-charts/configuration.md
Labels: type/documentation, scope/k8s

#3810 BE: RBAC: Add missing RBAC action, fix possible exceptions on unknown actions
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AccessController.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Labels: type/bug, type/enhancement, scope/backend

#3811 Infra: E2E: Add k-ui healthcheck
  .github/workflows/e2e-checks.yaml
Labels: scope/infrastructure

#3817 Checking Clear results in case of no result after execution
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/drivers/WebDriver.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/suite/TopicsTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/ksqldb/KsqlDbTest.java
Labels: scope/AQA

#3697 BE: Chore: Fix code style in internalConsumerGroup
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java
Labels: scope/backend, type/chore

#3829 logback-spring.xml format upd (removing deprecated `layout`)
  kafka-ui-api/src/main/resources/application.yml
  kafka-ui-api/src/main/resources/logback-spring.xml
Labels: scope/backend, type/chore

#3840 BE: Chore: CVEs fixes, May 2023
  kafka-ui-api/pom.xml
  pom.xml
Labels: scope/backend, type/security, type/chore

#3839 Infra: Update infra repo remote
  .github/workflows/aws_publisher.yaml
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  .github/workflows/master.yaml
  .github/workflows/separate_env_public_create.yml
  .github/workflows/separate_env_public_remove.yml
Labels: scope/infrastructure

#3849 Checking Broker's config search
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/BasePage.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/brokers/BrokersConfigTab.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/brokers/BrokersDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/brokers/BrokersList.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicDetails.java
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicsList.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/brokers/BrokersTest.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/TopicsTest.java
Labels: scope/AQA

#3833 FE: Fix latest version is null
  kafka-ui-react-app/src/components/Version/Version.tsx
Labels: type/bug, scope/frontend

#3827 FE: Fix version display with a tag
  kafka-ui-react-app/src/components/Version/Version.tsx
Labels: type/bug, scope/frontend

#3748 FE: Allow to edit active topic message filter
  kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicDetails.java
  kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/TopicsTest.java
  kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/EditFilter.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/FilterModal.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/EditFilter.spec.tsx
  kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/FilterModal.spec.tsx
  kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
  kafka-ui-react-app/src/components/common/Alert/Alert.tsx
  kafka-ui-react-app/src/components/common/Icons/CloseCircleIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/CloseIcon.tsx
  kafka-ui-react-app/src/components/common/Icons/EditIcon.tsx
  kafka-ui-react-app/src/components/common/Search/Search.tsx
  kafka-ui-react-app/src/theme/theme.ts
  kafka-ui-react-app/src/widgets/ClusterConfigForm/Sections/KafkaCluster.tsx
  kafka-ui-react-app/src/widgets/ClusterConfigForm/Sections/KafkaConnect.tsx
Labels: type/enhancement, scope/frontend

#3862 FE: Fix permissions check for cluster edit
  kafka-ui-react-app/src/components/Dashboard/ClusterTableActionsCell.tsx
  kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
Labels: type/bug, scope/frontend, type/regression

#3855 Chore: Update examples, configs
  documentation/compose/DOCKER_COMPOSE.md
  documentation/compose/data/message.json
  documentation/compose/data/proxy.conf
  documentation/compose/e2e-tests.yaml
  documentation/compose/kafka-cluster-sr-auth.yaml
  documentation/compose/kafka-clusters-only.yaml
  documentation/compose/kafka-ui-arm64.yaml
  documentation/compose/kafka-ui-connectors-auth.yaml
  documentation/compose/kafka-ui.yaml
  documentation/compose/kafka-with-zookeeper.yaml
  documentation/compose/ldap.yaml
  documentation/compose/nginx-proxy.yaml
  documentation/compose/oauth-cognito.yaml
  documentation/compose/traefik-proxy.yaml
  kafka-ui-api/src/main/resources/application-gauth.yml
  kafka-ui-api/src/main/resources/application-local.yml
  kafka-ui-api/src/main/resources/application-sdp.yml
Labels: type/chore, scope/infrastructure

#3881 BE: Make webclient use system proxy
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
Labels: type/bug, scope/backend

#3857 Minor serdes fixes
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdeInstance.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java
Labels: type/bug, scope/backend

#3826 renaming "messages behind" to "consumer lag"
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopicConsumerGroup.java
  kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java
  kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
  kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/TopicContents.tsx
  kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
  kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
  kafka-ui-react-app/src/lib/fixtures/consumerGroups.ts
  kafka-ui-react-app/src/lib/fixtures/topics.ts
Labels: scope/backend, scope/frontend, type/chore
